apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pgbackweb.fullname" . }}-config
  labels:
  {{- include "pgbackweb.labels" . | nindent 4 }}
data:
  PBW_ENCRYPTION_KEY: {{ .Values.config.pbwEncryptionKey | quote }}
  TZ: {{ .Values.config.tz | quote }}
  PBW_POSTGRES_CONN_STRING: {{ .Values.config.pbwPostgresConnectionString | quote }}