package staticdata

type Timezone struct {
	Label  string `json:"label"`
	TzCode string `json:"tzCode"`
	Name   string `json:"name"`
	Utc    string `json:"utc"`
}

var Timezones = []Timezone{
	{
		Label:  "UTC (GMT+00:00)",
		TzCode: "UTC",
		Name:   "(GMT+00:00) UTC",
		Utc:    "+00:00",
	},
	{
		Label:  "GMT (GMT+00:00)",
		TzCode: "GMT",
		Name:   "(GMT+00:00) GMT",
		Utc:    "+00:00",
	},
	{
		Label:  "Pacific/Midway (GMT-11:00)",
		TzCode: "Pacific/Midway",
		Name:   "(GMT-11:00) Midway",
		Utc:    "-11:00",
	},
	{
		Label:  "Pacific/Niue (GMT-11:00)",
		TzCode: "Pacific/Niue",
		Name:   "(GMT-11:00) Alofi",
		Utc:    "-11:00",
	},
	{
		Label:  "Pacific/Pago_Pago (GMT-11:00)",
		TzCode: "Pacific/Pago_Pago",
		Name:   "(GMT-11:00) Pago Pago, Tāfuna, Ta`ū, Taulaga",
		Utc:    "-11:00",
	},
	{
		Label:  "America/Adak (GMT-10:00)",
		TzCode: "America/Adak",
		Name:   "(GMT-10:00) Adak",
		Utc:    "-10:00",
	},
	{
		Label:  "Pacific/Honolulu (GMT-10:00)",
		TzCode: "Pacific/Honolulu",
		Name:   "(GMT-10:00) Honolulu, East Honolulu, Pearl City, Hilo, Kailua",
		Utc:    "-10:00",
	},
	{
		Label:  "Pacific/Rarotonga (GMT-10:00)",
		TzCode: "Pacific/Rarotonga",
		Name:   "(GMT-10:00) Avarua",
		Utc:    "-10:00",
	},
	{
		Label:  "Pacific/Tahiti (GMT-10:00)",
		TzCode: "Pacific/Tahiti",
		Name:   "(GMT-10:00) Faaa, Papeete, Punaauia, Pirae, Mahina",
		Utc:    "-10:00",
	},
	{
		Label:  "Pacific/Marquesas (GMT-09:30)",
		TzCode: "Pacific/Marquesas",
		Name:   "(GMT-09:30) Taiohae",
		Utc:    "-09:30",
	},
	{
		Label:  "America/Anchorage (GMT-09:00)",
		TzCode: "America/Anchorage",
		Name:   "(GMT-09:00) Anchorage, Fairbanks, Eagle River, Badger, Knik-Fairview",
		Utc:    "-09:00",
	},
	{
		Label:  "America/Juneau (GMT-09:00)",
		TzCode: "America/Juneau",
		Name:   "(GMT-09:00) Juneau",
		Utc:    "-09:00",
	},
	{
		Label:  "America/Metlakatla (GMT-09:00)",
		TzCode: "America/Metlakatla",
		Name:   "(GMT-09:00) Metlakatla",
		Utc:    "-09:00",
	},
	{
		Label:  "America/Nome (GMT-09:00)",
		TzCode: "America/Nome",
		Name:   "(GMT-09:00) Nome",
		Utc:    "-09:00",
	},
	{
		Label:  "America/Sitka (GMT-09:00)",
		TzCode: "America/Sitka",
		Name:   "(GMT-09:00) Sitka, Ketchikan",
		Utc:    "-09:00",
	},
	{
		Label:  "America/Yakutat (GMT-09:00)",
		TzCode: "America/Yakutat",
		Name:   "(GMT-09:00) Yakutat",
		Utc:    "-09:00",
	},
	{
		Label:  "Pacific/Gambier (GMT-09:00)",
		TzCode: "Pacific/Gambier",
		Name:   "(GMT-09:00) Gambier",
		Utc:    "-09:00",
	},
	{
		Label:  "America/Los_Angeles (GMT-08:00)",
		TzCode: "America/Los_Angeles",
		Name:   "(GMT-08:00) Los Angeles, San Diego, San Jose, San Francisco, Seattle",
		Utc:    "-08:00",
	},
	{
		Label:  "America/Tijuana (GMT-08:00)",
		TzCode: "America/Tijuana",
		Name:   "(GMT-08:00) Tijuana, Mexicali, Ensenada, Rosarito, Tecate",
		Utc:    "-08:00",
	},
	{
		Label:  "America/Vancouver (GMT-08:00)",
		TzCode: "America/Vancouver",
		Name:   "(GMT-08:00) Vancouver, Surrey, Okanagan, Victoria, Burnaby",
		Utc:    "-08:00",
	},
	{
		Label:  "Pacific/Pitcairn (GMT-08:00)",
		TzCode: "Pacific/Pitcairn",
		Name:   "(GMT-08:00) Adamstown",
		Utc:    "-08:00",
	},
	{
		Label:  "America/Boise (GMT-07:00)",
		TzCode: "America/Boise",
		Name:   "(GMT-07:00) Boise, Meridian, Nampa, Idaho Falls, Pocatello",
		Utc:    "-07:00",
	},
	{
		Label:  "America/Cambridge_Bay (GMT-07:00)",
		TzCode: "America/Cambridge_Bay",
		Name:   "(GMT-07:00) Cambridge Bay",
		Utc:    "-07:00",
	},
	{
		Label:  "America/Chihuahua (GMT-07:00)",
		TzCode: "America/Chihuahua",
		Name:   "(GMT-07:00) Chihuahua, Ciudad Delicias, Cuauhtémoc, Parral, Nuevo Casas Grandes",
		Utc:    "-07:00",
	},
	{
		Label:  "America/Creston (GMT-07:00)",
		TzCode: "America/Creston",
		Name:   "(GMT-07:00) Creston",
		Utc:    "-07:00",
	},
	{
		Label:  "America/Dawson (GMT-07:00)",
		TzCode: "America/Dawson",
		Name:   "(GMT-07:00) Dawson",
		Utc:    "-07:00",
	},
	{
		Label:  "America/Dawson_Creek (GMT-07:00)",
		TzCode: "America/Dawson_Creek",
		Name:   "(GMT-07:00) Fort St. John, Dawson Creek",
		Utc:    "-07:00",
	},
	{
		Label:  "America/Denver (GMT-07:00)",
		TzCode: "America/Denver",
		Name:   "(GMT-07:00) Denver, El Paso, Albuquerque, Colorado Springs, Aurora",
		Utc:    "-07:00",
	},
	{
		Label:  "America/Edmonton (GMT-07:00)",
		TzCode: "America/Edmonton",
		Name:   "(GMT-07:00) Calgary, Edmonton, Fort McMurray, Red Deer, Lethbridge",
		Utc:    "-07:00",
	},
	{
		Label:  "America/Fort_Nelson (GMT-07:00)",
		TzCode: "America/Fort_Nelson",
		Name:   "(GMT-07:00) Fort Nelson",
		Utc:    "-07:00",
	},
	{
		Label:  "America/Hermosillo (GMT-07:00)",
		TzCode: "America/Hermosillo",
		Name:   "(GMT-07:00) Hermosillo, Ciudad Obregón, Nogales, San Luis Río Colorado, Navojoa",
		Utc:    "-07:00",
	},
	{
		Label:  "America/Inuvik (GMT-07:00)",
		TzCode: "America/Inuvik",
		Name:   "(GMT-07:00) Inuvik",
		Utc:    "-07:00",
	},
	{
		Label:  "America/Mazatlan (GMT-07:00)",
		TzCode: "America/Mazatlan",
		Name:   "(GMT-07:00) Culiacán, Mazatlán, Tepic, Los Mochis, La Paz",
		Utc:    "-07:00",
	},
	{
		Label:  "America/Ojinaga (GMT-07:00)",
		TzCode: "America/Ojinaga",
		Name:   "(GMT-07:00) Ciudad Juárez, Manuel Ojinaga, Ojinaga",
		Utc:    "-07:00",
	},
	{
		Label:  "America/Phoenix (GMT-07:00)",
		TzCode: "America/Phoenix",
		Name:   "(GMT-07:00) Phoenix, Tucson, Mesa, Chandler, Gilbert",
		Utc:    "-07:00",
	},
	{
		Label:  "America/Whitehorse (GMT-07:00)",
		TzCode: "America/Whitehorse",
		Name:   "(GMT-07:00) Whitehorse",
		Utc:    "-07:00",
	},
	{
		Label:  "America/Yellowknife (GMT-07:00)",
		TzCode: "America/Yellowknife",
		Name:   "(GMT-07:00) Yellowknife",
		Utc:    "-07:00",
	},
	{
		Label:  "America/Bahia_Banderas (GMT-06:00)",
		TzCode: "America/Bahia_Banderas",
		Name:   "(GMT-06:00) Mezcales, San Vicente, Bucerías, Valle de Banderas",
		Utc:    "-06:00",
	},
	{
		Label:  "America/Belize (GMT-06:00)",
		TzCode: "America/Belize",
		Name:   "(GMT-06:00) Belize City, San Ignacio, Orange Walk, Belmopan, Dangriga",
		Utc:    "-06:00",
	},
	{
		Label:  "America/Chicago (GMT-06:00)",
		TzCode: "America/Chicago",
		Name:   "(GMT-06:00) Chicago, Houston, San Antonio, Dallas, Austin",
		Utc:    "-06:00",
	},
	{
		Label:  "America/Costa_Rica (GMT-06:00)",
		TzCode: "America/Costa_Rica",
		Name:   "(GMT-06:00) San José, Limón, San Francisco, Alajuela, Liberia",
		Utc:    "-06:00",
	},
	{
		Label:  "America/El_Salvador (GMT-06:00)",
		TzCode: "America/El_Salvador",
		Name:   "(GMT-06:00) San Salvador, Soyapango, Santa Ana, San Miguel, Mejicanos",
		Utc:    "-06:00",
	},
	{
		Label:  "America/Guatemala (GMT-06:00)",
		TzCode: "America/Guatemala",
		Name:   "(GMT-06:00) Guatemala City, Mixco, Villa Nueva, Petapa, San Juan Sacatepéquez",
		Utc:    "-06:00",
	},
	{
		Label:  "America/Indiana/Knox (GMT-06:00)",
		TzCode: "America/Indiana/Knox",
		Name:   "(GMT-06:00) Knox",
		Utc:    "-06:00",
	},
	{
		Label:  "America/Indiana/Tell_City (GMT-06:00)",
		TzCode: "America/Indiana/Tell_City",
		Name:   "(GMT-06:00) Tell City",
		Utc:    "-06:00",
	},
	{
		Label:  "America/Managua (GMT-06:00)",
		TzCode: "America/Managua",
		Name:   "(GMT-06:00) Managua, León, Masaya, Chinandega, Matagalpa",
		Utc:    "-06:00",
	},
	{
		Label:  "America/Matamoros (GMT-06:00)",
		TzCode: "America/Matamoros",
		Name:   "(GMT-06:00) Reynosa, Heroica Matamoros, Nuevo Laredo, Piedras Negras, Ciudad Acuña",
		Utc:    "-06:00",
	},
	{
		Label:  "America/Menominee (GMT-06:00)",
		TzCode: "America/Menominee",
		Name:   "(GMT-06:00) Menominee, Iron Mountain, Kingsford, Ironwood, Iron River",
		Utc:    "-06:00",
	},
	{
		Label:  "America/Merida (GMT-06:00)",
		TzCode: "America/Merida",
		Name:   "(GMT-06:00) Mérida, Campeche, Ciudad del Carmen, Kanasín, Valladolid",
		Utc:    "-06:00",
	},
	{
		Label:  "America/Mexico_City (GMT-06:00)",
		TzCode: "America/Mexico_City",
		Name:   "(GMT-06:00) Mexico City, Iztapalapa, Ecatepec de Morelos, Guadalajara, Puebla",
		Utc:    "-06:00",
	},
	{
		Label:  "America/Monterrey (GMT-06:00)",
		TzCode: "America/Monterrey",
		Name:   "(GMT-06:00) Monterrey, Saltillo, Guadalupe, Torreón, Victoria de Durango",
		Utc:    "-06:00",
	},
	{
		Label:  "America/North_Dakota/Beulah (GMT-06:00)",
		TzCode: "America/North_Dakota/Beulah",
		Name:   "(GMT-06:00) Beulah",
		Utc:    "-06:00",
	},
	{
		Label:  "America/North_Dakota/Center (GMT-06:00)",
		TzCode: "America/North_Dakota/Center",
		Name:   "(GMT-06:00) Center",
		Utc:    "-06:00",
	},
	{
		Label:  "America/North_Dakota/New_Salem (GMT-06:00)",
		TzCode: "America/North_Dakota/New_Salem",
		Name:   "(GMT-06:00) Mandan",
		Utc:    "-06:00",
	},
	{
		Label:  "America/Rainy_River (GMT-06:00)",
		TzCode: "America/Rainy_River",
		Name:   "(GMT-06:00) Rainy River",
		Utc:    "-06:00",
	},
	{
		Label:  "America/Rankin_Inlet (GMT-06:00)",
		TzCode: "America/Rankin_Inlet",
		Name:   "(GMT-06:00) Rankin Inlet",
		Utc:    "-06:00",
	},
	{
		Label:  "America/Regina (GMT-06:00)",
		TzCode: "America/Regina",
		Name:   "(GMT-06:00) Saskatoon, Regina, Prince Albert, Moose Jaw, North Battleford",
		Utc:    "-06:00",
	},
	{
		Label:  "America/Resolute (GMT-06:00)",
		TzCode: "America/Resolute",
		Name:   "(GMT-06:00) Resolute",
		Utc:    "-06:00",
	},
	{
		Label:  "America/Swift_Current (GMT-06:00)",
		TzCode: "America/Swift_Current",
		Name:   "(GMT-06:00) Swift Current",
		Utc:    "-06:00",
	},
	{
		Label:  "America/Tegucigalpa (GMT-06:00)",
		TzCode: "America/Tegucigalpa",
		Name:   "(GMT-06:00) Tegucigalpa, San Pedro Sula, Choloma, La Ceiba, El Progreso",
		Utc:    "-06:00",
	},
	{
		Label:  "America/Winnipeg (GMT-06:00)",
		TzCode: "America/Winnipeg",
		Name:   "(GMT-06:00) Winnipeg, Brandon, Kenora, Portage la Prairie, Thompson",
		Utc:    "-06:00",
	},
	{
		Label:  "Pacific/Easter (GMT-06:00)",
		TzCode: "Pacific/Easter",
		Name:   "(GMT-06:00) Easter",
		Utc:    "-06:00",
	},
	{
		Label:  "Pacific/Galapagos (GMT-06:00)",
		TzCode: "Pacific/Galapagos",
		Name:   "(GMT-06:00) Puerto Ayora, Puerto Baquerizo Moreno",
		Utc:    "-06:00",
	},
	{
		Label:  "America/Atikokan (GMT-05:00)",
		TzCode: "America/Atikokan",
		Name:   "(GMT-05:00) Atikokan",
		Utc:    "-05:00",
	},
	{
		Label:  "America/Bogota (GMT-05:00)",
		TzCode: "America/Bogota",
		Name:   "(GMT-05:00) Bogotá, Cali, Medellín, Barranquilla, Cartagena",
		Utc:    "-05:00",
	},
	{
		Label:  "America/Cancun (GMT-05:00)",
		TzCode: "America/Cancun",
		Name:   "(GMT-05:00) Cancún, Chetumal, Playa del Carmen, Cozumel, Felipe Carrillo Puerto",
		Utc:    "-05:00",
	},
	{
		Label:  "America/Cayman (GMT-05:00)",
		TzCode: "America/Cayman",
		Name:   "(GMT-05:00) George Town, West Bay, Bodden Town, East End, North Side",
		Utc:    "-05:00",
	},
	{
		Label:  "America/Detroit (GMT-05:00)",
		TzCode: "America/Detroit",
		Name:   "(GMT-05:00) Detroit, Grand Rapids, Warren, Sterling Heights, Ann Arbor",
		Utc:    "-05:00",
	},
	{
		Label:  "America/Eirunepe (GMT-05:00)",
		TzCode: "America/Eirunepe",
		Name:   "(GMT-05:00) Eirunepé, Benjamin Constant, Envira",
		Utc:    "-05:00",
	},
	{
		Label:  "America/Grand_Turk (GMT-05:00)",
		TzCode: "America/Grand_Turk",
		Name:   "(GMT-05:00) Cockburn Town",
		Utc:    "-05:00",
	},
	{
		Label:  "America/Guayaquil (GMT-05:00)",
		TzCode: "America/Guayaquil",
		Name:   "(GMT-05:00) Guayaquil, Quito, Cuenca, Santo Domingo de los Colorados, Machala",
		Utc:    "-05:00",
	},
	{
		Label:  "America/Havana (GMT-05:00)",
		TzCode: "America/Havana",
		Name:   "(GMT-05:00) Havana, Santiago de Cuba, Camagüey, Holguín, Guantánamo",
		Utc:    "-05:00",
	},
	{
		Label:  "America/Indiana/Indianapolis (GMT-05:00)",
		TzCode: "America/Indiana/Indianapolis",
		Name:   "(GMT-05:00) Indianapolis, Fort Wayne, South Bend, Carmel, Bloomington",
		Utc:    "-05:00",
	},
	{
		Label:  "America/Indiana/Marengo (GMT-05:00)",
		TzCode: "America/Indiana/Marengo",
		Name:   "(GMT-05:00) Marengo",
		Utc:    "-05:00",
	},
	{
		Label:  "America/Indiana/Petersburg (GMT-05:00)",
		TzCode: "America/Indiana/Petersburg",
		Name:   "(GMT-05:00) Petersburg",
		Utc:    "-05:00",
	},
	{
		Label:  "America/Indiana/Vevay (GMT-05:00)",
		TzCode: "America/Indiana/Vevay",
		Name:   "(GMT-05:00) Vevay",
		Utc:    "-05:00",
	},
	{
		Label:  "America/Indiana/Vincennes (GMT-05:00)",
		TzCode: "America/Indiana/Vincennes",
		Name:   "(GMT-05:00) Vincennes, Jasper, Washington, Huntingburg",
		Utc:    "-05:00",
	},
	{
		Label:  "America/Indiana/Winamac (GMT-05:00)",
		TzCode: "America/Indiana/Winamac",
		Name:   "(GMT-05:00) Winamac",
		Utc:    "-05:00",
	},
	{
		Label:  "America/Iqaluit (GMT-05:00)",
		TzCode: "America/Iqaluit",
		Name:   "(GMT-05:00) Iqaluit",
		Utc:    "-05:00",
	},
	{
		Label:  "America/Jamaica (GMT-05:00)",
		TzCode: "America/Jamaica",
		Name:   "(GMT-05:00) Kingston, New Kingston, Spanish Town, Portmore, Montego Bay",
		Utc:    "-05:00",
	},
	{
		Label:  "America/Kentucky/Louisville (GMT-05:00)",
		TzCode: "America/Kentucky/Louisville",
		Name:   "(GMT-05:00) Louisville, Jeffersonville, New Albany, Jeffersontown, Pleasure Ridge Park",
		Utc:    "-05:00",
	},
	{
		Label:  "America/Kentucky/Monticello (GMT-05:00)",
		TzCode: "America/Kentucky/Monticello",
		Name:   "(GMT-05:00) Monticello",
		Utc:    "-05:00",
	},
	{
		Label:  "America/Lima (GMT-05:00)",
		TzCode: "America/Lima",
		Name:   "(GMT-05:00) Lima, Arequipa, Callao, Trujillo, Chiclayo",
		Utc:    "-05:00",
	},
	{
		Label:  "America/Nassau (GMT-05:00)",
		TzCode: "America/Nassau",
		Name:   "(GMT-05:00) Nassau, Lucaya, Freeport, West End, Cooper’s Town",
		Utc:    "-05:00",
	},
	{
		Label:  "America/New_York (GMT-05:00)",
		TzCode: "America/New_York",
		Name:   "(GMT-05:00) New York City, Brooklyn, Queens, Philadelphia, Manhattan",
		Utc:    "-05:00",
	},
	{
		Label:  "America/Nipigon (GMT-05:00)",
		TzCode: "America/Nipigon",
		Name:   "(GMT-05:00) Nipigon",
		Utc:    "-05:00",
	},
	{
		Label:  "America/Panama (GMT-05:00)",
		TzCode: "America/Panama",
		Name:   "(GMT-05:00) Panamá, San Miguelito, Juan Díaz, David, Arraiján",
		Utc:    "-05:00",
	},
	{
		Label:  "America/Pangnirtung (GMT-05:00)",
		TzCode: "America/Pangnirtung",
		Name:   "(GMT-05:00) Pangnirtung",
		Utc:    "-05:00",
	},
	{
		Label:  "America/Port-au-Prince (GMT-05:00)",
		TzCode: "America/Port-au-Prince",
		Name:   "(GMT-05:00) Port-au-Prince, Carrefour, Delmas 73, Pétionville, Port-de-Paix",
		Utc:    "-05:00",
	},
	{
		Label:  "America/Rio_Branco (GMT-05:00)",
		TzCode: "America/Rio_Branco",
		Name:   "(GMT-05:00) Rio Branco, Cruzeiro do Sul, Sena Madureira, Tarauacá, Feijó",
		Utc:    "-05:00",
	},
	{
		Label:  "America/Thunder_Bay (GMT-05:00)",
		TzCode: "America/Thunder_Bay",
		Name:   "(GMT-05:00) Thunder Bay",
		Utc:    "-05:00",
	},
	{
		Label:  "America/Toronto (GMT-05:00)",
		TzCode: "America/Toronto",
		Name:   "(GMT-05:00) Toronto, Montréal, Ottawa, Mississauga, Québec",
		Utc:    "-05:00",
	},
	{
		Label:  "America/Anguilla (GMT-04:00)",
		TzCode: "America/Anguilla",
		Name:   "(GMT-04:00) The Valley, Blowing Point Village, Sandy Ground Village, The Quarter, Sandy Hill",
		Utc:    "-04:00",
	},
	{
		Label:  "America/Antigua (GMT-04:00)",
		TzCode: "America/Antigua",
		Name:   "(GMT-04:00) Saint John’s, Piggotts, Bolands, Codrington, Parham",
		Utc:    "-04:00",
	},
	{
		Label:  "America/Aruba (GMT-04:00)",
		TzCode: "America/Aruba",
		Name:   "(GMT-04:00) Oranjestad, Tanki Leendert, San Nicolas, Santa Cruz, Paradera",
		Utc:    "-04:00",
	},
	{
		Label:  "America/Asuncion (GMT-04:00)",
		TzCode: "America/Asuncion",
		Name:   "(GMT-04:00) Asunción, Ciudad del Este, San Lorenzo, Capiatá, Lambaré",
		Utc:    "-04:00",
	},
	{
		Label:  "America/Barbados (GMT-04:00)",
		TzCode: "America/Barbados",
		Name:   "(GMT-04:00) Bridgetown, Speightstown, Oistins, Bathsheba, Holetown",
		Utc:    "-04:00",
	},
	{
		Label:  "America/Blanc-Sablon (GMT-04:00)",
		TzCode: "America/Blanc-Sablon",
		Name:   "(GMT-04:00) Lévis",
		Utc:    "-04:00",
	},
	{
		Label:  "America/Boa_Vista (GMT-04:00)",
		TzCode: "America/Boa_Vista",
		Name:   "(GMT-04:00) Boa Vista",
		Utc:    "-04:00",
	},
	{
		Label:  "America/Campo_Grande (GMT-04:00)",
		TzCode: "America/Campo_Grande",
		Name:   "(GMT-04:00) Campo Grande, Dourados, Corumbá, Três Lagoas, Ponta Porã",
		Utc:    "-04:00",
	},
	{
		Label:  "America/Caracas (GMT-04:00)",
		TzCode: "America/Caracas",
		Name:   "(GMT-04:00) Caracas, Maracaibo, Maracay, Valencia, Barquisimeto",
		Utc:    "-04:00",
	},
	{
		Label:  "America/Cuiaba (GMT-04:00)",
		TzCode: "America/Cuiaba",
		Name:   "(GMT-04:00) Cuiabá, Várzea Grande, Rondonópolis, Sinop, Barra do Garças",
		Utc:    "-04:00",
	},
	{
		Label:  "America/Curacao (GMT-04:00)",
		TzCode: "America/Curacao",
		Name:   "(GMT-04:00) Willemstad, Sint Michiel Liber",
		Utc:    "-04:00",
	},
	{
		Label:  "America/Dominica (GMT-04:00)",
		TzCode: "America/Dominica",
		Name:   "(GMT-04:00) Roseau, Portsmouth, Berekua, Saint Joseph, Wesley",
		Utc:    "-04:00",
	},
	{
		Label:  "America/Glace_Bay (GMT-04:00)",
		TzCode: "America/Glace_Bay",
		Name:   "(GMT-04:00) Sydney, Glace Bay, Sydney Mines",
		Utc:    "-04:00",
	},
	{
		Label:  "America/Goose_Bay (GMT-04:00)",
		TzCode: "America/Goose_Bay",
		Name:   "(GMT-04:00) Labrador City, Happy Valley-Goose Bay",
		Utc:    "-04:00",
	},
	{
		Label:  "America/Grenada (GMT-04:00)",
		TzCode: "America/Grenada",
		Name:   "(GMT-04:00) Saint George's, Gouyave, Grenville, Victoria, Saint David’s",
		Utc:    "-04:00",
	},
	{
		Label:  "America/Guadeloupe (GMT-04:00)",
		TzCode: "America/Guadeloupe",
		Name:   "(GMT-04:00) Les Abymes, Baie-Mahault, Le Gosier, Petit-Bourg, Sainte-Anne",
		Utc:    "-04:00",
	},
	{
		Label:  "America/Guyana (GMT-04:00)",
		TzCode: "America/Guyana",
		Name:   "(GMT-04:00) Georgetown, Linden, New Amsterdam, Anna Regina, Bartica",
		Utc:    "-04:00",
	},
	{
		Label:  "America/Halifax (GMT-04:00)",
		TzCode: "America/Halifax",
		Name:   "(GMT-04:00) Halifax, Dartmouth, Charlottetown, Lower Sackville, Truro",
		Utc:    "-04:00",
	},
	{
		Label:  "America/Kralendijk (GMT-04:00)",
		TzCode: "America/Kralendijk",
		Name:   "(GMT-04:00) Kralendijk, Oranjestad, The Bottom",
		Utc:    "-04:00",
	},
	{
		Label:  "America/La_Paz (GMT-04:00)",
		TzCode: "America/La_Paz",
		Name:   "(GMT-04:00) Santa Cruz de la Sierra, Cochabamba, La Paz, Sucre, Oruro",
		Utc:    "-04:00",
	},
	{
		Label:  "America/Lower_Princes (GMT-04:00)",
		TzCode: "America/Lower_Princes",
		Name:   "(GMT-04:00) Cul de Sac, Lower Prince’s Quarter, Koolbaai, Philipsburg",
		Utc:    "-04:00",
	},
	{
		Label:  "America/Manaus (GMT-04:00)",
		TzCode: "America/Manaus",
		Name:   "(GMT-04:00) Manaus, Itacoatiara, Parintins, Manacapuru, Coari",
		Utc:    "-04:00",
	},
	{
		Label:  "America/Marigot (GMT-04:00)",
		TzCode: "America/Marigot",
		Name:   "(GMT-04:00) Marigot",
		Utc:    "-04:00",
	},
	{
		Label:  "America/Martinique (GMT-04:00)",
		TzCode: "America/Martinique",
		Name:   "(GMT-04:00) Fort-de-France, Le Lamentin, Le Robert, Sainte-Marie, Le François",
		Utc:    "-04:00",
	},
	{
		Label:  "America/Moncton (GMT-04:00)",
		TzCode: "America/Moncton",
		Name:   "(GMT-04:00) Moncton, Saint John, Fredericton, Dieppe, Miramichi",
		Utc:    "-04:00",
	},
	{
		Label:  "America/Montserrat (GMT-04:00)",
		TzCode: "America/Montserrat",
		Name:   "(GMT-04:00) Brades, Saint Peters, Plymouth",
		Utc:    "-04:00",
	},
	{
		Label:  "America/Porto_Velho (GMT-04:00)",
		TzCode: "America/Porto_Velho",
		Name:   "(GMT-04:00) Porto Velho, Ji Paraná, Vilhena, Ariquemes, Cacoal",
		Utc:    "-04:00",
	},
	{
		Label:  "America/Port_of_Spain (GMT-04:00)",
		TzCode: "America/Port_of_Spain",
		Name:   "(GMT-04:00) Chaguanas, Mon Repos, San Fernando, Port of Spain, Rio Claro",
		Utc:    "-04:00",
	},
	{
		Label:  "America/Puerto_Rico (GMT-04:00)",
		TzCode: "America/Puerto_Rico",
		Name:   "(GMT-04:00) San Juan, Bayamón, Carolina, Ponce, Caguas",
		Utc:    "-04:00",
	},
	{
		Label:  "America/Santiago (GMT-04:00)",
		TzCode: "America/Santiago",
		Name:   "(GMT-04:00) Santiago, Puente Alto, Antofagasta, Viña del Mar, Valparaíso",
		Utc:    "-04:00",
	},
	{
		Label:  "America/Santo_Domingo (GMT-04:00)",
		TzCode: "America/Santo_Domingo",
		Name:   "(GMT-04:00) Santo Domingo, Santiago de los Caballeros, Santo Domingo Oeste, Santo Domingo Este, San Pedro de Macorís",
		Utc:    "-04:00",
	},
	{
		Label:  "America/St_Barthelemy (GMT-04:00)",
		TzCode: "America/St_Barthelemy",
		Name:   "(GMT-04:00) Gustavia",
		Utc:    "-04:00",
	},
	{
		Label:  "America/St_Kitts (GMT-04:00)",
		TzCode: "America/St_Kitts",
		Name:   "(GMT-04:00) Basseterre, Fig Tree, Market Shop, Saint Paul’s, Middle Island",
		Utc:    "-04:00",
	},
	{
		Label:  "America/St_Lucia (GMT-04:00)",
		TzCode: "America/St_Lucia",
		Name:   "(GMT-04:00) Castries, Bisee, Vieux Fort, Micoud, Soufrière",
		Utc:    "-04:00",
	},
	{
		Label:  "America/St_Thomas (GMT-04:00)",
		TzCode: "America/St_Thomas",
		Name:   "(GMT-04:00) Saint Croix, Charlotte Amalie, Cruz Bay",
		Utc:    "-04:00",
	},
	{
		Label:  "America/St_Vincent (GMT-04:00)",
		TzCode: "America/St_Vincent",
		Name:   "(GMT-04:00) Kingstown, Kingstown Park, Georgetown, Barrouallie, Port Elizabeth",
		Utc:    "-04:00",
	},
	{
		Label:  "America/Thule (GMT-04:00)",
		TzCode: "America/Thule",
		Name:   "(GMT-04:00) Thule",
		Utc:    "-04:00",
	},
	{
		Label:  "America/Tortola (GMT-04:00)",
		TzCode: "America/Tortola",
		Name:   "(GMT-04:00) Road Town",
		Utc:    "-04:00",
	},
	{
		Label:  "Atlantic/Bermuda (GMT-04:00)",
		TzCode: "Atlantic/Bermuda",
		Name:   "(GMT-04:00) Hamilton",
		Utc:    "-04:00",
	},
	{
		Label:  "America/St_Johns (GMT-03:30)",
		TzCode: "America/St_Johns",
		Name:   "(GMT-03:30) St. John's, Mount Pearl, Corner Brook, Conception Bay South, Bay Roberts",
		Utc:    "-03:30",
	},
	{
		Label:  "America/Araguaina (GMT-03:00)",
		TzCode: "America/Araguaina",
		Name:   "(GMT-03:00) Palmas, Araguaína, Gurupi, Miracema do Tocantins, Porto Franco",
		Utc:    "-03:00",
	},
	{
		Label:  "America/Argentina/Buenos_Aires (GMT-03:00)",
		TzCode: "America/Argentina/Buenos_Aires",
		Name:   "(GMT-03:00) Buenos Aires, La Plata, Mar del Plata, Morón, Bahía Blanca",
		Utc:    "-03:00",
	},
	{
		Label:  "America/Argentina/Catamarca (GMT-03:00)",
		TzCode: "America/Argentina/Catamarca",
		Name:   "(GMT-03:00) San Fernando del Valle de Catamarca, Trelew, Puerto Madryn, Esquel, Rawson",
		Utc:    "-03:00",
	},
	{
		Label:  "America/Argentina/Cordoba (GMT-03:00)",
		TzCode: "America/Argentina/Cordoba",
		Name:   "(GMT-03:00) Córdoba, Rosario, Santa Fe, Resistencia, Santiago del Estero",
		Utc:    "-03:00",
	},
	{
		Label:  "America/Argentina/Jujuy (GMT-03:00)",
		TzCode: "America/Argentina/Jujuy",
		Name:   "(GMT-03:00) San Salvador de Jujuy, San Pedro de Jujuy, Libertador General San Martín, Palpalá, La Quiaca",
		Utc:    "-03:00",
	},
	{
		Label:  "America/Argentina/La_Rioja (GMT-03:00)",
		TzCode: "America/Argentina/La_Rioja",
		Name:   "(GMT-03:00) La Rioja, Chilecito, Arauco, Chamical",
		Utc:    "-03:00",
	},
	{
		Label:  "America/Argentina/Mendoza (GMT-03:00)",
		TzCode: "America/Argentina/Mendoza",
		Name:   "(GMT-03:00) Mendoza, San Rafael, San Martín",
		Utc:    "-03:00",
	},
	{
		Label:  "America/Argentina/Rio_Gallegos (GMT-03:00)",
		TzCode: "America/Argentina/Rio_Gallegos",
		Name:   "(GMT-03:00) Comodoro Rivadavia, Río Gallegos, Caleta Olivia, Pico Truncado, Puerto Deseado",
		Utc:    "-03:00",
	},
	{
		Label:  "America/Argentina/Salta (GMT-03:00)",
		TzCode: "America/Argentina/Salta",
		Name:   "(GMT-03:00) Salta, Neuquén, Santa Rosa, San Carlos de Bariloche, Cipolletti",
		Utc:    "-03:00",
	},
	{
		Label:  "America/Argentina/San_Juan (GMT-03:00)",
		TzCode: "America/Argentina/San_Juan",
		Name:   "(GMT-03:00) San Juan, Chimbas, Santa Lucía, Pocito, Caucete",
		Utc:    "-03:00",
	},
	{
		Label:  "America/Argentina/San_Luis (GMT-03:00)",
		TzCode: "America/Argentina/San_Luis",
		Name:   "(GMT-03:00) San Luis, Villa Mercedes, La Punta, Merlo, Justo Daract",
		Utc:    "-03:00",
	},
	{
		Label:  "America/Argentina/Tucuman (GMT-03:00)",
		TzCode: "America/Argentina/Tucuman",
		Name:   "(GMT-03:00) San Miguel de Tucumán, Yerba Buena, Tafí Viejo, Alderetes, Aguilares",
		Utc:    "-03:00",
	},
	{
		Label:  "America/Argentina/Ushuaia (GMT-03:00)",
		TzCode: "America/Argentina/Ushuaia",
		Name:   "(GMT-03:00) Ushuaia, Río Grande",
		Utc:    "-03:00",
	},
	{
		Label:  "America/Bahia (GMT-03:00)",
		TzCode: "America/Bahia",
		Name:   "(GMT-03:00) Salvador, Feira de Santana, Vitória da Conquista, Itabuna, Camaçari",
		Utc:    "-03:00",
	},
	{
		Label:  "America/Belem (GMT-03:00)",
		TzCode: "America/Belem",
		Name:   "(GMT-03:00) Belém, Ananindeua, Macapá, Parauapebas, Marabá",
		Utc:    "-03:00",
	},
	{
		Label:  "America/Cayenne (GMT-03:00)",
		TzCode: "America/Cayenne",
		Name:   "(GMT-03:00) Cayenne, Matoury, Saint-Laurent-du-Maroni, Kourou, Rémire-Montjoly",
		Utc:    "-03:00",
	},
	{
		Label:  "America/Fortaleza (GMT-03:00)",
		TzCode: "America/Fortaleza",
		Name:   "(GMT-03:00) Fortaleza, São Luís, Natal, Teresina, João Pessoa",
		Utc:    "-03:00",
	},
	{
		Label:  "America/Godthab (GMT-03:00)",
		TzCode: "America/Godthab",
		Name:   "(GMT-03:00) Nuuk, Sisimiut, Ilulissat, Qaqortoq, Aasiaat",
		Utc:    "-03:00",
	},
	{
		Label:  "America/Maceio (GMT-03:00)",
		TzCode: "America/Maceio",
		Name:   "(GMT-03:00) Maceió, Aracaju, Arapiraca, Nossa Senhora do Socorro, São Cristóvão",
		Utc:    "-03:00",
	},
	{
		Label:  "America/Miquelon (GMT-03:00)",
		TzCode: "America/Miquelon",
		Name:   "(GMT-03:00) Saint-Pierre, Miquelon",
		Utc:    "-03:00",
	},
	{
		Label:  "America/Montevideo (GMT-03:00)",
		TzCode: "America/Montevideo",
		Name:   "(GMT-03:00) Montevideo, Salto, Paysandú, Las Piedras, Rivera",
		Utc:    "-03:00",
	},
	{
		Label:  "America/Paramaribo (GMT-03:00)",
		TzCode: "America/Paramaribo",
		Name:   "(GMT-03:00) Paramaribo, Lelydorp, Brokopondo, Nieuw Nickerie, Moengo",
		Utc:    "-03:00",
	},
	{
		Label:  "America/Punta_Arenas (GMT-03:00)",
		TzCode: "America/Punta_Arenas",
		Name:   "(GMT-03:00) Punta Arenas, Puerto Natales",
		Utc:    "-03:00",
	},
	{
		Label:  "America/Recife (GMT-03:00)",
		TzCode: "America/Recife",
		Name:   "(GMT-03:00) Recife, Jaboatão, Jaboatão dos Guararapes, Olinda, Paulista",
		Utc:    "-03:00",
	},
	{
		Label:  "America/Santarem (GMT-03:00)",
		TzCode: "America/Santarem",
		Name:   "(GMT-03:00) Santarém, Altamira, Itaituba, Oriximiná, Alenquer",
		Utc:    "-03:00",
	},
	{
		Label:  "America/Sao_Paulo (GMT-03:00)",
		TzCode: "America/Sao_Paulo",
		Name:   "(GMT-03:00) São Paulo, Rio de Janeiro, Belo Horizonte, Brasília, Curitiba",
		Utc:    "-03:00",
	},
	{
		Label:  "Antarctica/Palmer (GMT-03:00)",
		TzCode: "Antarctica/Palmer",
		Name:   "(GMT-03:00) Palmer",
		Utc:    "-03:00",
	},
	{
		Label:  "Antarctica/Rothera (GMT-03:00)",
		TzCode: "Antarctica/Rothera",
		Name:   "(GMT-03:00) Rothera",
		Utc:    "-03:00",
	},
	{
		Label:  "Atlantic/Stanley (GMT-03:00)",
		TzCode: "Atlantic/Stanley",
		Name:   "(GMT-03:00) Stanley",
		Utc:    "-03:00",
	},
	{
		Label:  "America/Noronha (GMT-02:00)",
		TzCode: "America/Noronha",
		Name:   "(GMT-02:00) Itamaracá",
		Utc:    "-02:00",
	},
	{
		Label:  "Atlantic/South_Georgia (GMT-02:00)",
		TzCode: "Atlantic/South_Georgia",
		Name:   "(GMT-02:00) Grytviken",
		Utc:    "-02:00",
	},
	{
		Label:  "America/Scoresbysund (GMT-01:00)",
		TzCode: "America/Scoresbysund",
		Name:   "(GMT-01:00) Scoresbysund",
		Utc:    "-01:00",
	},
	{
		Label:  "Atlantic/Azores (GMT-01:00)",
		TzCode: "Atlantic/Azores",
		Name:   "(GMT-01:00) Ponta Delgada, Lagoa, Angra do Heroísmo, Rosto de Cão, Rabo de Peixe",
		Utc:    "-01:00",
	},
	{
		Label:  "Atlantic/Cape_Verde (GMT-01:00)",
		TzCode: "Atlantic/Cape_Verde",
		Name:   "(GMT-01:00) Praia, Mindelo, Santa Maria, Cova Figueira, Santa Cruz",
		Utc:    "-01:00",
	},
	{
		Label:  "Africa/Abidjan (GMT+00:00)",
		TzCode: "Africa/Abidjan",
		Name:   "(GMT+00:00) Abidjan, Abobo, Bouaké, Daloa, San-Pédro",
		Utc:    "+00:00",
	},
	{
		Label:  "Africa/Accra (GMT+00:00)",
		TzCode: "Africa/Accra",
		Name:   "(GMT+00:00) Accra, Kumasi, Tamale, Takoradi, Atsiaman",
		Utc:    "+00:00",
	},
	{
		Label:  "Africa/Bamako (GMT+00:00)",
		TzCode: "Africa/Bamako",
		Name:   "(GMT+00:00) Bamako, Sikasso, Mopti, Koutiala, Ségou",
		Utc:    "+00:00",
	},
	{
		Label:  "Africa/Banjul (GMT+00:00)",
		TzCode: "Africa/Banjul",
		Name:   "(GMT+00:00) Serekunda, Brikama, Bakau, Banjul, Farafenni",
		Utc:    "+00:00",
	},
	{
		Label:  "Africa/Bissau (GMT+00:00)",
		TzCode: "Africa/Bissau",
		Name:   "(GMT+00:00) Bissau, Bafatá, Gabú, Bissorã, Bolama",
		Utc:    "+00:00",
	},
	{
		Label:  "Africa/Casablanca (GMT+00:00)",
		TzCode: "Africa/Casablanca",
		Name:   "(GMT+00:00) Casablanca, Rabat, Fès, Sale, Marrakesh",
		Utc:    "+00:00",
	},
	{
		Label:  "Africa/Conakry (GMT+00:00)",
		TzCode: "Africa/Conakry",
		Name:   "(GMT+00:00) Camayenne, Conakry, Nzérékoré, Kindia, Kankan",
		Utc:    "+00:00",
	},
	{
		Label:  "Africa/Dakar (GMT+00:00)",
		TzCode: "Africa/Dakar",
		Name:   "(GMT+00:00) Dakar, Pikine, Touba, Thiès, Thiès Nones",
		Utc:    "+00:00",
	},
	{
		Label:  "Africa/El_Aaiun (GMT+00:00)",
		TzCode: "Africa/El_Aaiun",
		Name:   "(GMT+00:00) Laayoune, Dakhla, Laayoune Plage",
		Utc:    "+00:00",
	},
	{
		Label:  "Africa/Freetown (GMT+00:00)",
		TzCode: "Africa/Freetown",
		Name:   "(GMT+00:00) Freetown, Bo, Kenema, Koidu, Makeni",
		Utc:    "+00:00",
	},
	{
		Label:  "Africa/Lome (GMT+00:00)",
		TzCode: "Africa/Lome",
		Name:   "(GMT+00:00) Lomé, Sokodé, Kara, Atakpamé, Kpalimé",
		Utc:    "+00:00",
	},
	{
		Label:  "Africa/Monrovia (GMT+00:00)",
		TzCode: "Africa/Monrovia",
		Name:   "(GMT+00:00) Monrovia, Gbarnga, Kakata, Bensonville, Harper",
		Utc:    "+00:00",
	},
	{
		Label:  "Africa/Nouakchott (GMT+00:00)",
		TzCode: "Africa/Nouakchott",
		Name:   "(GMT+00:00) Nouakchott, Nouadhibou, Néma, Kaédi, Rosso",
		Utc:    "+00:00",
	},
	{
		Label:  "Africa/Ouagadougou (GMT+00:00)",
		TzCode: "Africa/Ouagadougou",
		Name:   "(GMT+00:00) Ouagadougou, Bobo-Dioulasso, Koudougou, Ouahigouya, Banfora",
		Utc:    "+00:00",
	},
	{
		Label:  "Africa/Sao_Tome (GMT+00:00)",
		TzCode: "Africa/Sao_Tome",
		Name:   "(GMT+00:00) São Tomé, Santo António",
		Utc:    "+00:00",
	},
	{
		Label:  "America/Danmarkshavn (GMT+00:00)",
		TzCode: "America/Danmarkshavn",
		Name:   "(GMT+00:00) Danmarkshavn",
		Utc:    "+00:00",
	},
	{
		Label:  "Antarctica/Troll (GMT+00:00)",
		TzCode: "Antarctica/Troll",
		Name:   "(GMT+00:00) Troll",
		Utc:    "+00:00",
	},
	{
		Label:  "Atlantic/Canary (GMT+00:00)",
		TzCode: "Atlantic/Canary",
		Name:   "(GMT+00:00) Las Palmas de Gran Canaria, Santa Cruz de Tenerife, La Laguna, Telde, Arona",
		Utc:    "+00:00",
	},
	{
		Label:  "Atlantic/Faroe (GMT+00:00)",
		TzCode: "Atlantic/Faroe",
		Name:   "(GMT+00:00) Tórshavn, Klaksvík, Fuglafjørður, Tvøroyri, Miðvágur",
		Utc:    "+00:00",
	},
	{
		Label:  "Atlantic/Madeira (GMT+00:00)",
		TzCode: "Atlantic/Madeira",
		Name:   "(GMT+00:00) Funchal, Câmara de Lobos, São Martinho, Caniço, Machico",
		Utc:    "+00:00",
	},
	{
		Label:  "Atlantic/Reykjavik (GMT+00:00)",
		TzCode: "Atlantic/Reykjavik",
		Name:   "(GMT+00:00) Reykjavík, Kópavogur, Hafnarfjörður, Akureyri, Garðabær",
		Utc:    "+00:00",
	},
	{
		Label:  "Atlantic/St_Helena (GMT+00:00)",
		TzCode: "Atlantic/St_Helena",
		Name:   "(GMT+00:00) Jamestown, Georgetown, Edinburgh of the Seven Seas",
		Utc:    "+00:00",
	},
	{
		Label:  "Europe/Dublin (GMT+00:00)",
		TzCode: "Europe/Dublin",
		Name:   "(GMT+00:00) Dublin, Cork, Luimneach, Gaillimh, Tallaght",
		Utc:    "+00:00",
	},
	{
		Label:  "Europe/Guernsey (GMT+00:00)",
		TzCode: "Europe/Guernsey",
		Name:   "(GMT+00:00) Saint Peter Port, St Martin, Saint Sampson, St Anne, Saint Saviour",
		Utc:    "+00:00",
	},
	{
		Label:  "Europe/Isle_of_Man (GMT+00:00)",
		TzCode: "Europe/Isle_of_Man",
		Name:   "(GMT+00:00) Douglas, Ramsey, Peel, Port Erin, Castletown",
		Utc:    "+00:00",
	},
	{
		Label:  "Europe/Jersey (GMT+00:00)",
		TzCode: "Europe/Jersey",
		Name:   "(GMT+00:00) Saint Helier, Le Hocq",
		Utc:    "+00:00",
	},
	{
		Label:  "Europe/Lisbon (GMT+00:00)",
		TzCode: "Europe/Lisbon",
		Name:   "(GMT+00:00) Lisbon, Porto, Amadora, Braga, Setúbal",
		Utc:    "+00:00",
	},
	{
		Label:  "Europe/London (GMT+00:00)",
		TzCode: "Europe/London",
		Name:   "(GMT+00:00) London, Birmingham, Liverpool, Sheffield, Bristol",
		Utc:    "+00:00",
	},
	{
		Label:  "Africa/Algiers (GMT+01:00)",
		TzCode: "Africa/Algiers",
		Name:   "(GMT+01:00) Algiers, Boumerdas, Oran, Tébessa, Constantine",
		Utc:    "+01:00",
	},
	{
		Label:  "Africa/Bangui (GMT+01:00)",
		TzCode: "Africa/Bangui",
		Name:   "(GMT+01:00) Bangui, Bimbo, Mbaïki, Berbérati, Kaga Bandoro",
		Utc:    "+01:00",
	},
	{
		Label:  "Africa/Brazzaville (GMT+01:00)",
		TzCode: "Africa/Brazzaville",
		Name:   "(GMT+01:00) Brazzaville, Pointe-Noire, Dolisie, Kayes, Owando",
		Utc:    "+01:00",
	},
	{
		Label:  "Africa/Ceuta (GMT+01:00)",
		TzCode: "Africa/Ceuta",
		Name:   "(GMT+01:00) Ceuta, Melilla",
		Utc:    "+01:00",
	},
	{
		Label:  "Africa/Douala (GMT+01:00)",
		TzCode: "Africa/Douala",
		Name:   "(GMT+01:00) Douala, Yaoundé, Garoua, Kousséri, Bamenda",
		Utc:    "+01:00",
	},
	{
		Label:  "Africa/Kinshasa (GMT+01:00)",
		TzCode: "Africa/Kinshasa",
		Name:   "(GMT+01:00) Kinshasa, Masina, Kikwit, Mbandaka, Matadi",
		Utc:    "+01:00",
	},
	{
		Label:  "Africa/Lagos (GMT+01:00)",
		TzCode: "Africa/Lagos",
		Name:   "(GMT+01:00) Lagos, Kano, Ibadan, Kaduna, Port Harcourt",
		Utc:    "+01:00",
	},
	{
		Label:  "Africa/Libreville (GMT+01:00)",
		TzCode: "Africa/Libreville",
		Name:   "(GMT+01:00) Libreville, Port-Gentil, Franceville, Oyem, Moanda",
		Utc:    "+01:00",
	},
	{
		Label:  "Africa/Luanda (GMT+01:00)",
		TzCode: "Africa/Luanda",
		Name:   "(GMT+01:00) Luanda, N’dalatando, Huambo, Lobito, Benguela",
		Utc:    "+01:00",
	},
	{
		Label:  "Africa/Malabo (GMT+01:00)",
		TzCode: "Africa/Malabo",
		Name:   "(GMT+01:00) Bata, Malabo, Ebebiyin, Aconibe, Añisoc",
		Utc:    "+01:00",
	},
	{
		Label:  "Africa/Ndjamena (GMT+01:00)",
		TzCode: "Africa/Ndjamena",
		Name:   "(GMT+01:00) N'Djamena, Moundou, Sarh, Abéché, Kelo",
		Utc:    "+01:00",
	},
	{
		Label:  "Africa/Niamey (GMT+01:00)",
		TzCode: "Africa/Niamey",
		Name:   "(GMT+01:00) Niamey, Zinder, Maradi, Agadez, Alaghsas",
		Utc:    "+01:00",
	},
	{
		Label:  "Africa/Porto-Novo (GMT+01:00)",
		TzCode: "Africa/Porto-Novo",
		Name:   "(GMT+01:00) Cotonou, Abomey-Calavi, Djougou, Porto-Novo, Parakou",
		Utc:    "+01:00",
	},
	{
		Label:  "Africa/Tunis (GMT+01:00)",
		TzCode: "Africa/Tunis",
		Name:   "(GMT+01:00) Tunis, Sfax, Sousse, Kairouan, Bizerte",
		Utc:    "+01:00",
	},
	{
		Label:  "Africa/Windhoek (GMT+01:00)",
		TzCode: "Africa/Windhoek",
		Name:   "(GMT+01:00) Windhoek, Rundu, Walvis Bay, Oshakati, Swakopmund",
		Utc:    "+01:00",
	},
	{
		Label:  "Arctic/Longyearbyen (GMT+01:00)",
		TzCode: "Arctic/Longyearbyen",
		Name:   "(GMT+01:00) Longyearbyen, Olonkinbyen",
		Utc:    "+01:00",
	},
	{
		Label:  "Europe/Amsterdam (GMT+01:00)",
		TzCode: "Europe/Amsterdam",
		Name:   "(GMT+01:00) Amsterdam, Rotterdam, The Hague, Utrecht, Eindhoven",
		Utc:    "+01:00",
	},
	{
		Label:  "Europe/Andorra (GMT+01:00)",
		TzCode: "Europe/Andorra",
		Name:   "(GMT+01:00) Andorra la Vella, les Escaldes, Encamp, Sant Julià de Lòria, la Massana",
		Utc:    "+01:00",
	},
	{
		Label:  "Europe/Belgrade (GMT+01:00)",
		TzCode: "Europe/Belgrade",
		Name:   "(GMT+01:00) Belgrade, Pristina, Niš, Novi Sad, Prizren",
		Utc:    "+01:00",
	},
	{
		Label:  "Europe/Berlin (GMT+01:00)",
		TzCode: "Europe/Berlin",
		Name:   "(GMT+01:00) Berlin, Hamburg, Munich, Köln, Frankfurt am Main",
		Utc:    "+01:00",
	},
	{
		Label:  "Europe/Bratislava (GMT+01:00)",
		TzCode: "Europe/Bratislava",
		Name:   "(GMT+01:00) Bratislava, Košice, Prešov, Nitra, Žilina",
		Utc:    "+01:00",
	},
	{
		Label:  "Europe/Brussels (GMT+01:00)",
		TzCode: "Europe/Brussels",
		Name:   "(GMT+01:00) Brussels, Antwerpen, Gent, Charleroi, Liège",
		Utc:    "+01:00",
	},
	{
		Label:  "Europe/Budapest (GMT+01:00)",
		TzCode: "Europe/Budapest",
		Name:   "(GMT+01:00) Budapest, Debrecen, Miskolc, Szeged, Pécs",
		Utc:    "+01:00",
	},
	{
		Label:  "Europe/Copenhagen (GMT+01:00)",
		TzCode: "Europe/Copenhagen",
		Name:   "(GMT+01:00) Copenhagen, Århus, Odense, Aalborg, Frederiksberg",
		Utc:    "+01:00",
	},
	{
		Label:  "Europe/Gibraltar (GMT+01:00)",
		TzCode: "Europe/Gibraltar",
		Name:   "(GMT+01:00) Gibraltar",
		Utc:    "+01:00",
	},
	{
		Label:  "Europe/Ljubljana (GMT+01:00)",
		TzCode: "Europe/Ljubljana",
		Name:   "(GMT+01:00) Ljubljana, Maribor, Celje, Kranj, Velenje",
		Utc:    "+01:00",
	},
	{
		Label:  "Europe/Luxembourg (GMT+01:00)",
		TzCode: "Europe/Luxembourg",
		Name:   "(GMT+01:00) Luxembourg, Esch-sur-Alzette, Dudelange, Schifflange, Bettembourg",
		Utc:    "+01:00",
	},
	{
		Label:  "Europe/Madrid (GMT+01:00)",
		TzCode: "Europe/Madrid",
		Name:   "(GMT+01:00) Madrid, Barcelona, Valencia, Sevilla, Zaragoza",
		Utc:    "+01:00",
	},
	{
		Label:  "Europe/Malta (GMT+01:00)",
		TzCode: "Europe/Malta",
		Name:   "(GMT+01:00) Birkirkara, Qormi, Mosta, Żabbar, San Pawl il-Baħar",
		Utc:    "+01:00",
	},
	{
		Label:  "Europe/Monaco (GMT+01:00)",
		TzCode: "Europe/Monaco",
		Name:   "(GMT+01:00) Monaco, Monte-Carlo, La Condamine",
		Utc:    "+01:00",
	},
	{
		Label:  "Europe/Oslo (GMT+01:00)",
		TzCode: "Europe/Oslo",
		Name:   "(GMT+01:00) Oslo, Bergen, Trondheim, Stavanger, Drammen",
		Utc:    "+01:00",
	},
	{
		Label:  "Europe/Paris (GMT+01:00)",
		TzCode: "Europe/Paris",
		Name:   "(GMT+01:00) Paris, Marseille, Lyon, Toulouse, Nice",
		Utc:    "+01:00",
	},
	{
		Label:  "Europe/Podgorica (GMT+01:00)",
		TzCode: "Europe/Podgorica",
		Name:   "(GMT+01:00) Podgorica, Nikšić, Herceg Novi, Pljevlja, Budva",
		Utc:    "+01:00",
	},
	{
		Label:  "Europe/Prague (GMT+01:00)",
		TzCode: "Europe/Prague",
		Name:   "(GMT+01:00) Prague, Brno, Ostrava, Pilsen, Olomouc",
		Utc:    "+01:00",
	},
	{
		Label:  "Europe/Rome (GMT+01:00)",
		TzCode: "Europe/Rome",
		Name:   "(GMT+01:00) Rome, Milan, Naples, Turin, Palermo",
		Utc:    "+01:00",
	},
	{
		Label:  "Europe/San_Marino (GMT+01:00)",
		TzCode: "Europe/San_Marino",
		Name:   "(GMT+01:00) Serravalle, Borgo Maggiore, San Marino, Domagnano, Fiorentino",
		Utc:    "+01:00",
	},
	{
		Label:  "Europe/Sarajevo (GMT+01:00)",
		TzCode: "Europe/Sarajevo",
		Name:   "(GMT+01:00) Sarajevo, Banja Luka, Zenica, Tuzla, Mostar",
		Utc:    "+01:00",
	},
	{
		Label:  "Europe/Skopje (GMT+01:00)",
		TzCode: "Europe/Skopje",
		Name:   "(GMT+01:00) Skopje, Bitola, Kumanovo, Prilep, Tetovo",
		Utc:    "+01:00",
	},
	{
		Label:  "Europe/Stockholm (GMT+01:00)",
		TzCode: "Europe/Stockholm",
		Name:   "(GMT+01:00) Stockholm, Göteborg, Malmö, Uppsala, Sollentuna",
		Utc:    "+01:00",
	},
	{
		Label:  "Europe/Tirane (GMT+01:00)",
		TzCode: "Europe/Tirane",
		Name:   "(GMT+01:00) Tirana, Durrës, Elbasan, Vlorë, Shkodër",
		Utc:    "+01:00",
	},
	{
		Label:  "Europe/Vaduz (GMT+01:00)",
		TzCode: "Europe/Vaduz",
		Name:   "(GMT+01:00) Schaan, Vaduz, Triesen, Balzers, Eschen",
		Utc:    "+01:00",
	},
	{
		Label:  "Europe/Vatican (GMT+01:00)",
		TzCode: "Europe/Vatican",
		Name:   "(GMT+01:00) Vatican City",
		Utc:    "+01:00",
	},
	{
		Label:  "Europe/Vienna (GMT+01:00)",
		TzCode: "Europe/Vienna",
		Name:   "(GMT+01:00) Vienna, Graz, Linz, Favoriten, Donaustadt",
		Utc:    "+01:00",
	},
	{
		Label:  "Europe/Warsaw (GMT+01:00)",
		TzCode: "Europe/Warsaw",
		Name:   "(GMT+01:00) Warsaw, Łódź, Kraków, Wrocław, Poznań",
		Utc:    "+01:00",
	},
	{
		Label:  "Europe/Zagreb (GMT+01:00)",
		TzCode: "Europe/Zagreb",
		Name:   "(GMT+01:00) Zagreb, Split, Rijeka, Osijek, Zadar",
		Utc:    "+01:00",
	},
	{
		Label:  "Europe/Zurich (GMT+01:00)",
		TzCode: "Europe/Zurich",
		Name:   "(GMT+01:00) Zürich, Genève, Basel, Lausanne, Bern",
		Utc:    "+01:00",
	},
	{
		Label:  "Africa/Blantyre (GMT+02:00)",
		TzCode: "Africa/Blantyre",
		Name:   "(GMT+02:00) Lilongwe, Blantyre, Mzuzu, Zomba, Kasungu",
		Utc:    "+02:00",
	},
	{
		Label:  "Africa/Bujumbura (GMT+02:00)",
		TzCode: "Africa/Bujumbura",
		Name:   "(GMT+02:00) Bujumbura, Muyinga, Gitega, Ruyigi, Ngozi",
		Utc:    "+02:00",
	},
	{
		Label:  "Africa/Cairo (GMT+02:00)",
		TzCode: "Africa/Cairo",
		Name:   "(GMT+02:00) Cairo, Alexandria, Giza, Port Said, Suez",
		Utc:    "+02:00",
	},
	{
		Label:  "Africa/Gaborone (GMT+02:00)",
		TzCode: "Africa/Gaborone",
		Name:   "(GMT+02:00) Gaborone, Francistown, Molepolole, Selebi-Phikwe, Maun",
		Utc:    "+02:00",
	},
	{
		Label:  "Africa/Harare (GMT+02:00)",
		TzCode: "Africa/Harare",
		Name:   "(GMT+02:00) Harare, Bulawayo, Chitungwiza, Mutare, Gweru",
		Utc:    "+02:00",
	},
	{
		Label:  "Africa/Johannesburg (GMT+02:00)",
		TzCode: "Africa/Johannesburg",
		Name:   "(GMT+02:00) Cape Town, Durban, Johannesburg, Soweto, Pretoria",
		Utc:    "+02:00",
	},
	{
		Label:  "Africa/Juba (GMT+02:00)",
		TzCode: "Africa/Juba",
		Name:   "(GMT+02:00) Juba, Winejok, Malakal, Wau, Kuacjok",
		Utc:    "+02:00",
	},
	{
		Label:  "Africa/Khartoum (GMT+02:00)",
		TzCode: "Africa/Khartoum",
		Name:   "(GMT+02:00) Khartoum, Omdurman, Nyala, Port Sudan, Kassala",
		Utc:    "+02:00",
	},
	{
		Label:  "Africa/Kigali (GMT+02:00)",
		TzCode: "Africa/Kigali",
		Name:   "(GMT+02:00) Kigali, Butare, Gitarama, Musanze, Gisenyi",
		Utc:    "+02:00",
	},
	{
		Label:  "Africa/Lubumbashi (GMT+02:00)",
		TzCode: "Africa/Lubumbashi",
		Name:   "(GMT+02:00) Lubumbashi, Mbuji-Mayi, Kisangani, Kananga, Likasi",
		Utc:    "+02:00",
	},
	{
		Label:  "Africa/Lusaka (GMT+02:00)",
		TzCode: "Africa/Lusaka",
		Name:   "(GMT+02:00) Lusaka, Kitwe, Ndola, Kabwe, Chingola",
		Utc:    "+02:00",
	},
	{
		Label:  "Africa/Maputo (GMT+02:00)",
		TzCode: "Africa/Maputo",
		Name:   "(GMT+02:00) Maputo, Matola, Beira, Nampula, Chimoio",
		Utc:    "+02:00",
	},
	{
		Label:  "Africa/Maseru (GMT+02:00)",
		TzCode: "Africa/Maseru",
		Name:   "(GMT+02:00) Maseru, Mafeteng, Leribe, Maputsoe, Mohale’s Hoek",
		Utc:    "+02:00",
	},
	{
		Label:  "Africa/Mbabane (GMT+02:00)",
		TzCode: "Africa/Mbabane",
		Name:   "(GMT+02:00) Manzini, Mbabane, Big Bend, Malkerns, Nhlangano",
		Utc:    "+02:00",
	},
	{
		Label:  "Africa/Tripoli (GMT+02:00)",
		TzCode: "Africa/Tripoli",
		Name:   "(GMT+02:00) Tripoli, Benghazi, Mişrātah, Tarhuna, Al Khums",
		Utc:    "+02:00",
	},
	{
		Label:  "Asia/Amman (GMT+02:00)",
		TzCode: "Asia/Amman",
		Name:   "(GMT+02:00) Amman, Zarqa, Irbid, Russeifa, Wādī as Sīr",
		Utc:    "+02:00",
	},
	{
		Label:  "Asia/Beirut (GMT+02:00)",
		TzCode: "Asia/Beirut",
		Name:   "(GMT+02:00) Beirut, Ra’s Bayrūt, Tripoli, Sidon, Tyre",
		Utc:    "+02:00",
	},
	{
		Label:  "Asia/Damascus (GMT+02:00)",
		TzCode: "Asia/Damascus",
		Name:   "(GMT+02:00) Aleppo, Damascus, Homs, Ḩamāh, Latakia",
		Utc:    "+02:00",
	},
	{
		Label:  "Asia/Famagusta (GMT+02:00)",
		TzCode: "Asia/Famagusta",
		Name:   "(GMT+02:00) Famagusta, Kyrenia, Protaras, Paralímni, Lápithos",
		Utc:    "+02:00",
	},
	{
		Label:  "Asia/Gaza (GMT+02:00)",
		TzCode: "Asia/Gaza",
		Name:   "(GMT+02:00) Gaza, Khān Yūnis, Jabālyā, Rafaḩ, Dayr al Balaḩ",
		Utc:    "+02:00",
	},
	{
		Label:  "Asia/Hebron (GMT+02:00)",
		TzCode: "Asia/Hebron",
		Name:   "(GMT+02:00) East Jerusalem, Hebron, Nablus, Battir, Ţūlkarm",
		Utc:    "+02:00",
	},
	{
		Label:  "Asia/Jerusalem (GMT+02:00)",
		TzCode: "Asia/Jerusalem",
		Name:   "(GMT+02:00) Jerusalem, Tel Aviv, West Jerusalem, Haifa, Ashdod",
		Utc:    "+02:00",
	},
	{
		Label:  "Asia/Nicosia (GMT+02:00)",
		TzCode: "Asia/Nicosia",
		Name:   "(GMT+02:00) Nicosia, Limassol, Larnaca, Stróvolos, Paphos",
		Utc:    "+02:00",
	},
	{
		Label:  "Europe/Athens (GMT+02:00)",
		TzCode: "Europe/Athens",
		Name:   "(GMT+02:00) Athens, Thessaloníki, Pátra, Piraeus, Lárisa",
		Utc:    "+02:00",
	},
	{
		Label:  "Europe/Bucharest (GMT+02:00)",
		TzCode: "Europe/Bucharest",
		Name:   "(GMT+02:00) Bucharest, Sector 3, Sector 6, Sector 2, Iaşi",
		Utc:    "+02:00",
	},
	{
		Label:  "Europe/Chisinau (GMT+02:00)",
		TzCode: "Europe/Chisinau",
		Name:   "(GMT+02:00) Chisinau, Tiraspol, Bălţi, Bender, Rîbniţa",
		Utc:    "+02:00",
	},
	{
		Label:  "Europe/Helsinki (GMT+02:00)",
		TzCode: "Europe/Helsinki",
		Name:   "(GMT+02:00) Helsinki, Espoo, Tampere, Vantaa, Turku",
		Utc:    "+02:00",
	},
	{
		Label:  "Europe/Kaliningrad (GMT+02:00)",
		TzCode: "Europe/Kaliningrad",
		Name:   "(GMT+02:00) Kaliningrad, Chernyakhovsk, Sovetsk, Baltiysk, Gusev",
		Utc:    "+02:00",
	},
	{
		Label:  "Europe/Kyiv (GMT+02:00)",
		TzCode: "Europe/Kyiv",
		Name:   "(GMT+02:00) Kyiv, Kharkiv, Donetsk, Odesa, Dnipro",
		Utc:    "+02:00",
	},
	{
		Label:  "Europe/Mariehamn (GMT+02:00)",
		TzCode: "Europe/Mariehamn",
		Name:   "(GMT+02:00) Mariehamn",
		Utc:    "+02:00",
	},
	{
		Label:  "Europe/Riga (GMT+02:00)",
		TzCode: "Europe/Riga",
		Name:   "(GMT+02:00) Riga, Daugavpils, Liepāja, Jelgava, Jūrmala",
		Utc:    "+02:00",
	},
	{
		Label:  "Europe/Sofia (GMT+02:00)",
		TzCode: "Europe/Sofia",
		Name:   "(GMT+02:00) Sofia, Plovdiv, Varna, Burgas, Ruse",
		Utc:    "+02:00",
	},
	{
		Label:  "Europe/Tallinn (GMT+02:00)",
		TzCode: "Europe/Tallinn",
		Name:   "(GMT+02:00) Tallinn, Tartu, Narva, Kohtla-Järve, Pärnu",
		Utc:    "+02:00",
	},
	{
		Label:  "Europe/Uzhgorod (GMT+02:00)",
		TzCode: "Europe/Uzhgorod",
		Name:   "(GMT+02:00) Uzhgorod, Mukachevo, Khust, Berehove, Tyachiv",
		Utc:    "+02:00",
	},
	{
		Label:  "Europe/Vilnius (GMT+02:00)",
		TzCode: "Europe/Vilnius",
		Name:   "(GMT+02:00) Vilnius, Kaunas, Klaipėda, Šiauliai, Panevėžys",
		Utc:    "+02:00",
	},
	{
		Label:  "Africa/Addis_Ababa (GMT+03:00)",
		TzCode: "Africa/Addis_Ababa",
		Name:   "(GMT+03:00) Addis Ababa, Dire Dawa, Mek'ele, Nazrēt, Bahir Dar",
		Utc:    "+03:00",
	},
	{
		Label:  "Africa/Asmara (GMT+03:00)",
		TzCode: "Africa/Asmara",
		Name:   "(GMT+03:00) Asmara, Keren, Massawa, Assab, Mendefera",
		Utc:    "+03:00",
	},
	{
		Label:  "Africa/Dar_es_Salaam (GMT+03:00)",
		TzCode: "Africa/Dar_es_Salaam",
		Name:   "(GMT+03:00) Dar es Salaam, Mwanza, Zanzibar, Arusha, Mbeya",
		Utc:    "+03:00",
	},
	{
		Label:  "Africa/Djibouti (GMT+03:00)",
		TzCode: "Africa/Djibouti",
		Name:   "(GMT+03:00) Djibouti, 'Ali Sabieh, Tadjourah, Obock, Dikhil",
		Utc:    "+03:00",
	},
	{
		Label:  "Africa/Kampala (GMT+03:00)",
		TzCode: "Africa/Kampala",
		Name:   "(GMT+03:00) Kampala, Gulu, Lira, Mbarara, Jinja",
		Utc:    "+03:00",
	},
	{
		Label:  "Africa/Mogadishu (GMT+03:00)",
		TzCode: "Africa/Mogadishu",
		Name:   "(GMT+03:00) Mogadishu, Hargeysa, Berbera, Kismayo, Marka",
		Utc:    "+03:00",
	},
	{
		Label:  "Africa/Nairobi (GMT+03:00)",
		TzCode: "Africa/Nairobi",
		Name:   "(GMT+03:00) Nairobi, Mombasa, Nakuru, Eldoret, Kisumu",
		Utc:    "+03:00",
	},
	{
		Label:  "Antarctica/Syowa (GMT+03:00)",
		TzCode: "Antarctica/Syowa",
		Name:   "(GMT+03:00) Syowa",
		Utc:    "+03:00",
	},
	{
		Label:  "Asia/Aden (GMT+03:00)",
		TzCode: "Asia/Aden",
		Name:   "(GMT+03:00) Sanaa, Al Ḩudaydah, Taiz, Aden, Mukalla",
		Utc:    "+03:00",
	},
	{
		Label:  "Asia/Baghdad (GMT+03:00)",
		TzCode: "Asia/Baghdad",
		Name:   "(GMT+03:00) Baghdad, Basrah, Al Mawşil al Jadīdah, Al Başrah al Qadīmah, Mosul",
		Utc:    "+03:00",
	},
	{
		Label:  "Asia/Bahrain (GMT+03:00)",
		TzCode: "Asia/Bahrain",
		Name:   "(GMT+03:00) Manama, Al Muharraq, Ar Rifā‘, Dār Kulayb, Madīnat Ḩamad",
		Utc:    "+03:00",
	},
	{
		Label:  "Asia/Kuwait (GMT+03:00)",
		TzCode: "Asia/Kuwait",
		Name:   "(GMT+03:00) Al Aḩmadī, Ḩawallī, As Sālimīyah, Şabāḩ as Sālim, Al Farwānīyah",
		Utc:    "+03:00",
	},
	{
		Label:  "Asia/Qatar (GMT+03:00)",
		TzCode: "Asia/Qatar",
		Name:   "(GMT+03:00) Doha, Ar Rayyān, Umm Şalāl Muḩammad, Al Wakrah, Al Khawr",
		Utc:    "+03:00",
	},
	{
		Label:  "Asia/Riyadh (GMT+03:00)",
		TzCode: "Asia/Riyadh",
		Name:   "(GMT+03:00) Riyadh, Jeddah, Mecca, Medina, Sulţānah",
		Utc:    "+03:00",
	},
	{
		Label:  "Europe/Istanbul (GMT+03:00)",
		TzCode: "Europe/Istanbul",
		Name:   "(GMT+03:00) Istanbul, Ankara, İzmir, Bursa, Adana",
		Utc:    "+03:00",
	},
	{
		Label:  "Europe/Kirov (GMT+03:00)",
		TzCode: "Europe/Kirov",
		Name:   "(GMT+03:00) Kirov, Kirovo-Chepetsk, Vyatskiye Polyany, Slobodskoy, Kotel’nich",
		Utc:    "+03:00",
	},
	{
		Label:  "Europe/Minsk (GMT+03:00)",
		TzCode: "Europe/Minsk",
		Name:   "(GMT+03:00) Minsk, Homyel', Mahilyow, Vitebsk, Hrodna",
		Utc:    "+03:00",
	},
	{
		Label:  "Europe/Moscow (GMT+03:00)",
		TzCode: "Europe/Moscow",
		Name:   "(GMT+03:00) Moscow, Saint Petersburg, Nizhniy Novgorod, Kazan, Rostov-na-Donu",
		Utc:    "+03:00",
	},
	{
		Label:  "Europe/Simferopol (GMT+03:00)",
		TzCode: "Europe/Simferopol",
		Name:   "(GMT+03:00) Simferopol, Kerch, Yevpatoriya, Yalta, Feodosiya",
		Utc:    "+03:00",
	},
	{
		Label:  "Europe/Volgograd (GMT+03:00)",
		TzCode: "Europe/Volgograd",
		Name:   "(GMT+03:00) Volgograd, Volzhskiy, Kamyshin, Mikhaylovka, Uryupinsk",
		Utc:    "+03:00",
	},
	{
		Label:  "Indian/Antananarivo (GMT+03:00)",
		TzCode: "Indian/Antananarivo",
		Name:   "(GMT+03:00) Antananarivo, Toamasina, Antsirabe, Fianarantsoa, Mahajanga",
		Utc:    "+03:00",
	},
	{
		Label:  "Indian/Comoro (GMT+03:00)",
		TzCode: "Indian/Comoro",
		Name:   "(GMT+03:00) Moroni, Moutsamoudou, Fomboni, Domoni, Tsimbeo",
		Utc:    "+03:00",
	},
	{
		Label:  "Indian/Mayotte (GMT+03:00)",
		TzCode: "Indian/Mayotte",
		Name:   "(GMT+03:00) Mamoudzou, Koungou, Dzaoudzi, Dembeni, Sada",
		Utc:    "+03:00",
	},
	{
		Label:  "Asia/Tehran (GMT+03:30)",
		TzCode: "Asia/Tehran",
		Name:   "(GMT+03:30) Tehran, Mashhad, Isfahan, Karaj, Tabriz",
		Utc:    "+03:30",
	},
	{
		Label:  "Asia/Baku (GMT+04:00)",
		TzCode: "Asia/Baku",
		Name:   "(GMT+04:00) Baku, Ganja, Sumqayıt, Lankaran, Yevlakh",
		Utc:    "+04:00",
	},
	{
		Label:  "Asia/Dubai (GMT+04:00)",
		TzCode: "Asia/Dubai",
		Name:   "(GMT+04:00) Dubai, Sharjah, Abu Dhabi, Ajman City, Ras Al Khaimah City",
		Utc:    "+04:00",
	},
	{
		Label:  "Asia/Muscat (GMT+04:00)",
		TzCode: "Asia/Muscat",
		Name:   "(GMT+04:00) Muscat, Seeb, Şalālah, Bawshar, Sohar",
		Utc:    "+04:00",
	},
	{
		Label:  "Asia/Tbilisi (GMT+04:00)",
		TzCode: "Asia/Tbilisi",
		Name:   "(GMT+04:00) Tbilisi, Kutaisi, Batumi, Sokhumi, Zugdidi",
		Utc:    "+04:00",
	},
	{
		Label:  "Asia/Yerevan (GMT+04:00)",
		TzCode: "Asia/Yerevan",
		Name:   "(GMT+04:00) Yerevan, Gyumri, Vanadzor, Vagharshapat, Hrazdan",
		Utc:    "+04:00",
	},
	{
		Label:  "Europe/Astrakhan (GMT+04:00)",
		TzCode: "Europe/Astrakhan",
		Name:   "(GMT+04:00) Astrakhan, Akhtubinsk, Znamensk, Kharabali, Kamyzyak",
		Utc:    "+04:00",
	},
	{
		Label:  "Europe/Samara (GMT+04:00)",
		TzCode: "Europe/Samara",
		Name:   "(GMT+04:00) Samara, Togliatti-on-the-Volga, Izhevsk, Syzran’, Novokuybyshevsk",
		Utc:    "+04:00",
	},
	{
		Label:  "Europe/Saratov (GMT+04:00)",
		TzCode: "Europe/Saratov",
		Name:   "(GMT+04:00) Saratov, Balakovo, Engel’s, Balashov, Vol’sk",
		Utc:    "+04:00",
	},
	{
		Label:  "Europe/Ulyanovsk (GMT+04:00)",
		TzCode: "Europe/Ulyanovsk",
		Name:   "(GMT+04:00) Ulyanovsk, Dimitrovgrad, Inza, Barysh, Novoul’yanovsk",
		Utc:    "+04:00",
	},
	{
		Label:  "Indian/Mahe (GMT+04:00)",
		TzCode: "Indian/Mahe",
		Name:   "(GMT+04:00) Victoria, Anse Boileau, Bel Ombre, Beau Vallon, Cascade",
		Utc:    "+04:00",
	},
	{
		Label:  "Indian/Mauritius (GMT+04:00)",
		TzCode: "Indian/Mauritius",
		Name:   "(GMT+04:00) Port Louis, Beau Bassin-Rose Hill, Vacoas, Curepipe, Quatre Bornes",
		Utc:    "+04:00",
	},
	{
		Label:  "Indian/Reunion (GMT+04:00)",
		TzCode: "Indian/Reunion",
		Name:   "(GMT+04:00) Saint-Denis, Saint-Paul, Saint-Pierre, Le Tampon, Saint-André",
		Utc:    "+04:00",
	},
	{
		Label:  "Asia/Kabul (GMT+04:30)",
		TzCode: "Asia/Kabul",
		Name:   "(GMT+04:30) Kabul, Kandahār, Mazār-e Sharīf, Herāt, Jalālābād",
		Utc:    "+04:30",
	},
	{
		Label:  "Antarctica/Mawson (GMT+05:00)",
		TzCode: "Antarctica/Mawson",
		Name:   "(GMT+05:00) Mawson",
		Utc:    "+05:00",
	},
	{
		Label:  "Asia/Aqtau (GMT+05:00)",
		TzCode: "Asia/Aqtau",
		Name:   "(GMT+05:00) Shevchenko, Zhanaozen, Beyneu, Shetpe, Yeraliyev",
		Utc:    "+05:00",
	},
	{
		Label:  "Asia/Aqtobe (GMT+05:00)",
		TzCode: "Asia/Aqtobe",
		Name:   "(GMT+05:00) Aktobe, Kandyagash, Shalqar, Khromtau, Embi",
		Utc:    "+05:00",
	},
	{
		Label:  "Asia/Ashgabat (GMT+05:00)",
		TzCode: "Asia/Ashgabat",
		Name:   "(GMT+05:00) Ashgabat, Türkmenabat, Daşoguz, Mary, Balkanabat",
		Utc:    "+05:00",
	},
	{
		Label:  "Asia/Atyrau (GMT+05:00)",
		TzCode: "Asia/Atyrau",
		Name:   "(GMT+05:00) Atyrau, Qulsary, Shalkar, Balykshi, Maqat",
		Utc:    "+05:00",
	},
	{
		Label:  "Asia/Dushanbe (GMT+05:00)",
		TzCode: "Asia/Dushanbe",
		Name:   "(GMT+05:00) Dushanbe, Khujand, Kŭlob, Bokhtar, Istaravshan",
		Utc:    "+05:00",
	},
	{
		Label:  "Asia/Karachi (GMT+05:00)",
		TzCode: "Asia/Karachi",
		Name:   "(GMT+05:00) Karachi, Lahore, Faisalabad, Rawalpindi, Multan",
		Utc:    "+05:00",
	},
	{
		Label:  "Asia/Oral (GMT+05:00)",
		TzCode: "Asia/Oral",
		Name:   "(GMT+05:00) Oral, Aqsay, Zhänibek, Tasqala, Zhumysker",
		Utc:    "+05:00",
	},
	{
		Label:  "Asia/Qyzylorda (GMT+05:00)",
		TzCode: "Asia/Qyzylorda",
		Name:   "(GMT+05:00) Kyzylorda, Baikonur, Novokazalinsk, Aral, Chiili",
		Utc:    "+05:00",
	},
	{
		Label:  "Asia/Samarkand (GMT+05:00)",
		TzCode: "Asia/Samarkand",
		Name:   "(GMT+05:00) Samarkand, Bukhara, Nukus, Qarshi, Jizzax",
		Utc:    "+05:00",
	},
	{
		Label:  "Asia/Tashkent (GMT+05:00)",
		TzCode: "Asia/Tashkent",
		Name:   "(GMT+05:00) Tashkent, Namangan, Andijon, Qo‘qon, Chirchiq",
		Utc:    "+05:00",
	},
	{
		Label:  "Asia/Yekaterinburg (GMT+05:00)",
		TzCode: "Asia/Yekaterinburg",
		Name:   "(GMT+05:00) Yekaterinburg, Chelyabinsk, Ufa, Perm, Orenburg",
		Utc:    "+05:00",
	},
	{
		Label:  "Indian/Kerguelen (GMT+05:00)",
		TzCode: "Indian/Kerguelen",
		Name:   "(GMT+05:00) Port-aux-Français",
		Utc:    "+05:00",
	},
	{
		Label:  "Indian/Maldives (GMT+05:00)",
		TzCode: "Indian/Maldives",
		Name:   "(GMT+05:00) Male, Fuvahmulah, Hithadhoo, Kulhudhuffushi, Thinadhoo",
		Utc:    "+05:00",
	},
	{
		Label:  "Asia/Colombo (GMT+05:30)",
		TzCode: "Asia/Colombo",
		Name:   "(GMT+05:30) Colombo, Dehiwala-Mount Lavinia, Moratuwa, Jaffna, Negombo",
		Utc:    "+05:30",
	},
	{
		Label:  "Asia/Kolkata (GMT+05:30)",
		TzCode: "Asia/Kolkata",
		Name:   "(GMT+05:30) Mumbai, Delhi, Bengaluru, Kolkata, Chennai",
		Utc:    "+05:30",
	},
	{
		Label:  "Asia/Kathmandu (GMT+05:45)",
		TzCode: "Asia/Kathmandu",
		Name:   "(GMT+05:45) Kathmandu, Pokhara, Pātan, Biratnagar, Birgañj",
		Utc:    "+05:45",
	},
	{
		Label:  "Antarctica/Vostok (GMT+06:00)",
		TzCode: "Antarctica/Vostok",
		Name:   "(GMT+06:00) Vostok",
		Utc:    "+06:00",
	},
	{
		Label:  "Asia/Almaty (GMT+06:00)",
		TzCode: "Asia/Almaty",
		Name:   "(GMT+06:00) Almaty, Karagandy, Shymkent, Taraz, Nur-Sultan",
		Utc:    "+06:00",
	},
	{
		Label:  "Asia/Bishkek (GMT+06:00)",
		TzCode: "Asia/Bishkek",
		Name:   "(GMT+06:00) Bishkek, Osh, Jalal-Abad, Karakol, Tokmok",
		Utc:    "+06:00",
	},
	{
		Label:  "Asia/Dhaka (GMT+06:00)",
		TzCode: "Asia/Dhaka",
		Name:   "(GMT+06:00) Dhaka, Chattogram, Khulna, Rājshāhi, Comilla",
		Utc:    "+06:00",
	},
	{
		Label:  "Asia/Omsk (GMT+06:00)",
		TzCode: "Asia/Omsk",
		Name:   "(GMT+06:00) Omsk, Tara, Kalachinsk, Znamenskoye, Tavricheskoye",
		Utc:    "+06:00",
	},
	{
		Label:  "Asia/Qostanay (GMT+06:00)",
		TzCode: "Asia/Qostanay",
		Name:   "(GMT+06:00) Kostanay, Rudnyy, Dzhetygara, Arkalyk, Lisakovsk",
		Utc:    "+06:00",
	},
	{
		Label:  "Asia/Thimphu (GMT+06:00)",
		TzCode: "Asia/Thimphu",
		Name:   "(GMT+06:00) himphu, Punākha, Tsirang, Phuntsholing, Pemagatshel",
		Utc:    "+06:00",
	},
	{
		Label:  "Asia/Urumqi (GMT+06:00)",
		TzCode: "Asia/Urumqi",
		Name:   "(GMT+06:00) Zhongshan, Ürümqi, Zhanjiang, Shihezi, Huocheng",
		Utc:    "+06:00",
	},
	{
		Label:  "Indian/Chagos (GMT+06:00)",
		TzCode: "Indian/Chagos",
		Name:   "(GMT+06:00) British Indian Ocean Territory",
		Utc:    "+06:00",
	},
	{
		Label:  "Asia/Yangon (GMT+06:30)",
		TzCode: "Asia/Yangon",
		Name:   "(GMT+06:30) Yangon, Mandalay, Nay Pyi Taw, Mawlamyine, Kyain Seikgyi Township",
		Utc:    "+06:30",
	},
	{
		Label:  "Indian/Cocos (GMT+06:30)",
		TzCode: "Indian/Cocos",
		Name:   "(GMT+06:30) West Island",
		Utc:    "+06:30",
	},
	{
		Label:  "Antarctica/Davis (GMT+07:00)",
		TzCode: "Antarctica/Davis",
		Name:   "(GMT+07:00) Davis",
		Utc:    "+07:00",
	},
	{
		Label:  "Asia/Bangkok (GMT+07:00)",
		TzCode: "Asia/Bangkok",
		Name:   "(GMT+07:00) Bangkok, Hanoi, Haiphong, Samut Prakan, Mueang Nonthaburi",
		Utc:    "+07:00",
	},
	{
		Label:  "Asia/Barnaul (GMT+07:00)",
		TzCode: "Asia/Barnaul",
		Name:   "(GMT+07:00) Barnaul, Biysk, Rubtsovsk, Novoaltaysk, Gorno-Altaysk",
		Utc:    "+07:00",
	},
	{
		Label:  "Asia/Hovd (GMT+07:00)",
		TzCode: "Asia/Hovd",
		Name:   "(GMT+07:00) Khovd, Ölgii, Ulaangom, Uliastay, Altai",
		Utc:    "+07:00",
	},
	{
		Label:  "Asia/Ho_Chi_Minh (GMT+07:00)",
		TzCode: "Asia/Ho_Chi_Minh",
		Name:   "(GMT+07:00) Ho Chi Minh City, Da Nang, Biên Hòa, Nha Trang, Cần Thơ",
		Utc:    "+07:00",
	},
	{
		Label:  "Asia/Jakarta (GMT+07:00)",
		TzCode: "Asia/Jakarta",
		Name:   "(GMT+07:00) Jakarta, Surabaya, Medan, Bandung, Bekasi",
		Utc:    "+07:00",
	},
	{
		Label:  "Asia/Krasnoyarsk (GMT+07:00)",
		TzCode: "Asia/Krasnoyarsk",
		Name:   "(GMT+07:00) Krasnoyarsk, Abakan, Norilsk, Achinsk, Kyzyl",
		Utc:    "+07:00",
	},
	{
		Label:  "Asia/Novokuznetsk (GMT+07:00)",
		TzCode: "Asia/Novokuznetsk",
		Name:   "(GMT+07:00) Novokuznetsk, Kemerovo, Prokop’yevsk, Leninsk-Kuznetsky, Kiselëvsk",
		Utc:    "+07:00",
	},
	{
		Label:  "Asia/Novosibirsk (GMT+07:00)",
		TzCode: "Asia/Novosibirsk",
		Name:   "(GMT+07:00) Novosibirsk, Berdsk, Iskitim, Akademgorodok, Kuybyshev",
		Utc:    "+07:00",
	},
	{
		Label:  "Asia/Phnom_Penh (GMT+07:00)",
		TzCode: "Asia/Phnom_Penh",
		Name:   "(GMT+07:00) Phnom Penh, Takeo, Sihanoukville, Battambang, Siem Reap",
		Utc:    "+07:00",
	},
	{
		Label:  "Asia/Pontianak (GMT+07:00)",
		TzCode: "Asia/Pontianak",
		Name:   "(GMT+07:00) Pontianak, Tanjung Pinang, Palangkaraya, Singkawang, Sampit",
		Utc:    "+07:00",
	},
	{
		Label:  "Asia/Tomsk (GMT+07:00)",
		TzCode: "Asia/Tomsk",
		Name:   "(GMT+07:00) Tomsk, Seversk, Strezhevoy, Kolpashevo, Asino",
		Utc:    "+07:00",
	},
	{
		Label:  "Asia/Vientiane (GMT+07:00)",
		TzCode: "Asia/Vientiane",
		Name:   "(GMT+07:00) Vientiane, Pakse, Thakhèk, Savannakhet, Luang Prabang",
		Utc:    "+07:00",
	},
	{
		Label:  "Indian/Christmas (GMT+07:00)",
		TzCode: "Indian/Christmas",
		Name:   "(GMT+07:00) Flying Fish Cove",
		Utc:    "+07:00",
	},
	{
		Label:  "Asia/Brunei (GMT+08:00)",
		TzCode: "Asia/Brunei",
		Name:   "(GMT+08:00) Bandar Seri Begawan, Kuala Belait, Seria, Tutong, Bangar",
		Utc:    "+08:00",
	},
	{
		Label:  "Asia/Choibalsan (GMT+08:00)",
		TzCode: "Asia/Choibalsan",
		Name:   "(GMT+08:00) Baruun-Urt, Choibalsan",
		Utc:    "+08:00",
	},
	{
		Label:  "Asia/Hong_Kong (GMT+08:00)",
		TzCode: "Asia/Hong_Kong",
		Name:   "(GMT+08:00) Hong Kong, Kowloon, Tsuen Wan, Yuen Long Kau Hui, Tung Chung",
		Utc:    "+08:00",
	},
	{
		Label:  "Asia/Irkutsk (GMT+08:00)",
		TzCode: "Asia/Irkutsk",
		Name:   "(GMT+08:00) Irkutsk, Ulan-Ude, Bratsk, Angarsk, Ust’-Ilimsk",
		Utc:    "+08:00",
	},
	{
		Label:  "Asia/Kuala_Lumpur (GMT+08:00)",
		TzCode: "Asia/Kuala_Lumpur",
		Name:   "(GMT+08:00) Kota Bharu, Kuala Lumpur, Klang, Kampung Baru Subang, Johor Bahru",
		Utc:    "+08:00",
	},
	{
		Label:  "Asia/Kuching (GMT+08:00)",
		TzCode: "Asia/Kuching",
		Name:   "(GMT+08:00) Kuching, Kota Kinabalu, Sandakan, Tawau, Miri",
		Utc:    "+08:00",
	},
	{
		Label:  "Asia/Macau (GMT+08:00)",
		TzCode: "Asia/Macau",
		Name:   "(GMT+08:00) Macau",
		Utc:    "+08:00",
	},
	{
		Label:  "Asia/Makassar (GMT+08:00)",
		TzCode: "Asia/Makassar",
		Name:   "(GMT+08:00) Makassar, Denpasar, City of Balikpapan, Banjarmasin, Manado",
		Utc:    "+08:00",
	},
	{
		Label:  "Asia/Manila (GMT+08:00)",
		TzCode: "Asia/Manila",
		Name:   "(GMT+08:00) Quezon City, Manila, Caloocan City, Budta, Davao",
		Utc:    "+08:00",
	},
	{
		Label:  "Asia/Shanghai (GMT+08:00)",
		TzCode: "Asia/Shanghai",
		Name:   "(GMT+08:00) Shanghai, Beijing, Tianjin, Guangzhou, Shenzhen",
		Utc:    "+08:00",
	},
	{
		Label:  "Asia/Singapore (GMT+08:00)",
		TzCode: "Asia/Singapore",
		Name:   "(GMT+08:00) Singapore, Woodlands",
		Utc:    "+08:00",
	},
	{
		Label:  "Asia/Taipei (GMT+08:00)",
		TzCode: "Asia/Taipei",
		Name:   "(GMT+08:00) Taipei, Kaohsiung, Taichung, Tainan, Banqiao",
		Utc:    "+08:00",
	},
	{
		Label:  "Asia/Ulaanbaatar (GMT+08:00)",
		TzCode: "Asia/Ulaanbaatar",
		Name:   "(GMT+08:00) Ulan Bator, Erdenet, Darhan, Hovd, Mörön",
		Utc:    "+08:00",
	},
	{
		Label:  "Australia/Perth (GMT+08:00)",
		TzCode: "Australia/Perth",
		Name:   "(GMT+08:00) Perth, Rockingham, Mandurah, Bunbury, Albany",
		Utc:    "+08:00",
	},
	{
		Label:  "Australia/Eucla (GMT+08:45)",
		TzCode: "Australia/Eucla",
		Name:   "(GMT+08:45) Eucla",
		Utc:    "+08:45",
	},
	{
		Label:  "Asia/Chita (GMT+09:00)",
		TzCode: "Asia/Chita",
		Name:   "(GMT+09:00) Chita, Krasnokamensk, Borzya, Petrovsk-Zabaykal’skiy, Aginskoye",
		Utc:    "+09:00",
	},
	{
		Label:  "Asia/Dili (GMT+09:00)",
		TzCode: "Asia/Dili",
		Name:   "(GMT+09:00) Dili, Maliana, Suai, Likisá, Aileu",
		Utc:    "+09:00",
	},
	{
		Label:  "Asia/Jayapura (GMT+09:00)",
		TzCode: "Asia/Jayapura",
		Name:   "(GMT+09:00) Ambon, Jayapura, Sorong, Ternate, Abepura",
		Utc:    "+09:00",
	},
	{
		Label:  "Asia/Khandyga (GMT+09:00)",
		TzCode: "Asia/Khandyga",
		Name:   "(GMT+09:00) Khandyga",
		Utc:    "+09:00",
	},
	{
		Label:  "Asia/Pyongyang (GMT+09:00)",
		TzCode: "Asia/Pyongyang",
		Name:   "(GMT+09:00) Pyongyang, Hamhŭng, Namp’o, Sunch’ŏn, Hŭngnam",
		Utc:    "+09:00",
	},
	{
		Label:  "Asia/Seoul (GMT+09:00)",
		TzCode: "Asia/Seoul",
		Name:   "(GMT+09:00) Seoul, Busan, Incheon, Daegu, Daejeon",
		Utc:    "+09:00",
	},
	{
		Label:  "Asia/Tokyo (GMT+09:00)",
		TzCode: "Asia/Tokyo",
		Name:   "(GMT+09:00) Tokyo, Yokohama, Osaka, Nagoya, Sapporo",
		Utc:    "+09:00",
	},
	{
		Label:  "Asia/Yakutsk (GMT+09:00)",
		TzCode: "Asia/Yakutsk",
		Name:   "(GMT+09:00) Yakutsk, Blagoveshchensk, Belogorsk, Neryungri, Svobodnyy",
		Utc:    "+09:00",
	},
	{
		Label:  "Pacific/Palau (GMT+09:00)",
		TzCode: "Pacific/Palau",
		Name:   "(GMT+09:00) Koror, Koror Town, Kloulklubed, Ulimang, Mengellang",
		Utc:    "+09:00",
	},
	{
		Label:  "Australia/Adelaide (GMT+09:30)",
		TzCode: "Australia/Adelaide",
		Name:   "(GMT+09:30) Adelaide, Adelaide Hills, Mount Gambier, Morphett Vale, Gawler",
		Utc:    "+09:30",
	},
	{
		Label:  "Australia/Broken_Hill (GMT+09:30)",
		TzCode: "Australia/Broken_Hill",
		Name:   "(GMT+09:30) Broken Hill",
		Utc:    "+09:30",
	},
	{
		Label:  "Australia/Darwin (GMT+09:30)",
		TzCode: "Australia/Darwin",
		Name:   "(GMT+09:30) Darwin, Alice Springs, Palmerston, Howard Springs",
		Utc:    "+09:30",
	},
	{
		Label:  "Antarctica/DumontDUrville (GMT+10:00)",
		TzCode: "Antarctica/DumontDUrville",
		Name:   "(GMT+10:00) DumontDUrville",
		Utc:    "+10:00",
	},
	{
		Label:  "Antarctica/Macquarie (GMT+10:00)",
		TzCode: "Antarctica/Macquarie",
		Name:   "(GMT+10:00) Macquarie",
		Utc:    "+10:00",
	},
	{
		Label:  "Asia/Ust-Nera (GMT+10:00)",
		TzCode: "Asia/Ust-Nera",
		Name:   "(GMT+10:00) Ust-Nera",
		Utc:    "+10:00",
	},
	{
		Label:  "Asia/Vladivostok (GMT+10:00)",
		TzCode: "Asia/Vladivostok",
		Name:   "(GMT+10:00) Vladivostok, Khabarovsk, Khabarovsk Vtoroy, Komsomolsk-on-Amur, Ussuriysk",
		Utc:    "+10:00",
	},
	{
		Label:  "Australia/Brisbane (GMT+10:00)",
		TzCode: "Australia/Brisbane",
		Name:   "(GMT+10:00) Brisbane, Gold Coast, Logan City, Townsville, Cairns",
		Utc:    "+10:00",
	},
	{
		Label:  "Australia/Currie (GMT+10:00)",
		TzCode: "Australia/Currie",
		Name:   "(GMT+10:00) Currie",
		Utc:    "+10:00",
	},
	{
		Label:  "Australia/Hobart (GMT+10:00)",
		TzCode: "Australia/Hobart",
		Name:   "(GMT+10:00) Hobart, Launceston, Burnie, Devonport, Sandy Bay",
		Utc:    "+10:00",
	},
	{
		Label:  "Australia/Lindeman (GMT+10:00)",
		TzCode: "Australia/Lindeman",
		Name:   "(GMT+10:00) Lindeman",
		Utc:    "+10:00",
	},
	{
		Label:  "Australia/Melbourne (GMT+10:00)",
		TzCode: "Australia/Melbourne",
		Name:   "(GMT+10:00) Melbourne, Geelong, Bendigo, Ballarat, Melbourne City Centre",
		Utc:    "+10:00",
	},
	{
		Label:  "Australia/Sydney (GMT+10:00)",
		TzCode: "Australia/Sydney",
		Name:   "(GMT+10:00) Sydney, Canberra, Newcastle, Wollongong, Maitland",
		Utc:    "+10:00",
	},
	{
		Label:  "Pacific/Chuuk (GMT+10:00)",
		TzCode: "Pacific/Chuuk",
		Name:   "(GMT+10:00) Weno, Colonia",
		Utc:    "+10:00",
	},
	{
		Label:  "Pacific/Guam (GMT+10:00)",
		TzCode: "Pacific/Guam",
		Name:   "(GMT+10:00) Dededo Village, Yigo Village, Tamuning, Tamuning-Tumon-Harmon Village, Mangilao Village",
		Utc:    "+10:00",
	},
	{
		Label:  "Pacific/Port_Moresby (GMT+10:00)",
		TzCode: "Pacific/Port_Moresby",
		Name:   "(GMT+10:00) Port Moresby, Lae, Mount Hagen, Popondetta, Madang",
		Utc:    "+10:00",
	},
	{
		Label:  "Pacific/Saipan (GMT+10:00)",
		TzCode: "Pacific/Saipan",
		Name:   "(GMT+10:00) Saipan, San Jose Village",
		Utc:    "+10:00",
	},
	{
		Label:  "Australia/Lord_Howe (GMT+10:30)",
		TzCode: "Australia/Lord_Howe",
		Name:   "(GMT+10:30) Lord Howe",
		Utc:    "+10:30",
	},
	{
		Label:  "Antarctica/Casey (GMT+11:00)",
		TzCode: "Antarctica/Casey",
		Name:   "(GMT+11:00) Casey",
		Utc:    "+11:00",
	},
	{
		Label:  "Asia/Magadan (GMT+11:00)",
		TzCode: "Asia/Magadan",
		Name:   "(GMT+11:00) Magadan, Ust-Nera, Susuman, Ola",
		Utc:    "+11:00",
	},
	{
		Label:  "Asia/Sakhalin (GMT+11:00)",
		TzCode: "Asia/Sakhalin",
		Name:   "(GMT+11:00) Yuzhno-Sakhalinsk, Korsakov, Kholmsk, Okha, Nevel’sk",
		Utc:    "+11:00",
	},
	{
		Label:  "Asia/Srednekolymsk (GMT+11:00)",
		TzCode: "Asia/Srednekolymsk",
		Name:   "(GMT+11:00) Srednekolymsk",
		Utc:    "+11:00",
	},
	{
		Label:  "Pacific/Bougainville (GMT+11:00)",
		TzCode: "Pacific/Bougainville",
		Name:   "(GMT+11:00) Arawa, Buka",
		Utc:    "+11:00",
	},
	{
		Label:  "Pacific/Efate (GMT+11:00)",
		TzCode: "Pacific/Efate",
		Name:   "(GMT+11:00) Port-Vila, Luganville, Isangel, Sola, Lakatoro",
		Utc:    "+11:00",
	},
	{
		Label:  "Pacific/Guadalcanal (GMT+11:00)",
		TzCode: "Pacific/Guadalcanal",
		Name:   "(GMT+11:00) Honiara, Malango, Auki, Gizo, Buala",
		Utc:    "+11:00",
	},
	{
		Label:  "Pacific/Kosrae (GMT+11:00)",
		TzCode: "Pacific/Kosrae",
		Name:   "(GMT+11:00) Tofol",
		Utc:    "+11:00",
	},
	{
		Label:  "Pacific/Norfolk (GMT+11:00)",
		TzCode: "Pacific/Norfolk",
		Name:   "(GMT+11:00) Kingston",
		Utc:    "+11:00",
	},
	{
		Label:  "Pacific/Noumea (GMT+11:00)",
		TzCode: "Pacific/Noumea",
		Name:   "(GMT+11:00) Nouméa, Mont-Dore, Dumbéa, Païta, Wé",
		Utc:    "+11:00",
	},
	{
		Label:  "Pacific/Pohnpei (GMT+11:00)",
		TzCode: "Pacific/Pohnpei",
		Name:   "(GMT+11:00) Kolonia, Kolonia Town, Palikir - National Government Center",
		Utc:    "+11:00",
	},
	{
		Label:  "Antarctica/McMurdo (GMT+12:00)",
		TzCode: "Antarctica/McMurdo",
		Name:   "(GMT+12:00) McMurdo",
		Utc:    "+12:00",
	},
	{
		Label:  "Asia/Anadyr (GMT+12:00)",
		TzCode: "Asia/Anadyr",
		Name:   "(GMT+12:00) Anadyr, Bilibino",
		Utc:    "+12:00",
	},
	{
		Label:  "Asia/Kamchatka (GMT+12:00)",
		TzCode: "Asia/Kamchatka",
		Name:   "(GMT+12:00) Petropavlovsk-Kamchatsky, Yelizovo, Vilyuchinsk, Klyuchi, Mil’kovo",
		Utc:    "+12:00",
	},
	{
		Label:  "Pacific/Auckland (GMT+12:00)",
		TzCode: "Pacific/Auckland",
		Name:   "(GMT+12:00) Auckland, Wellington, Christchurch, Manukau City, North Shore",
		Utc:    "+12:00",
	},
	{
		Label:  "Pacific/Fiji (GMT+12:00)",
		TzCode: "Pacific/Fiji",
		Name:   "(GMT+12:00) Suva, Lautoka, Nadi, Labasa, Ba",
		Utc:    "+12:00",
	},
	{
		Label:  "Pacific/Funafuti (GMT+12:00)",
		TzCode: "Pacific/Funafuti",
		Name:   "(GMT+12:00) Funafuti, Savave Village, Tanrake Village, Toga Village, Asau Village",
		Utc:    "+12:00",
	},
	{
		Label:  "Pacific/Kwajalein (GMT+12:00)",
		TzCode: "Pacific/Kwajalein",
		Name:   "(GMT+12:00) Ebaye, Jabat",
		Utc:    "+12:00",
	},
	{
		Label:  "Pacific/Majuro (GMT+12:00)",
		TzCode: "Pacific/Majuro",
		Name:   "(GMT+12:00) Majuro, Arno, Jabor, Wotje, Mili",
		Utc:    "+12:00",
	},
	{
		Label:  "Pacific/Nauru (GMT+12:00)",
		TzCode: "Pacific/Nauru",
		Name:   "(GMT+12:00) Yaren, Baiti, Anabar, Uaboe, Ijuw",
		Utc:    "+12:00",
	},
	{
		Label:  "Pacific/Tarawa (GMT+12:00)",
		TzCode: "Pacific/Tarawa",
		Name:   "(GMT+12:00) Tarawa, Betio Village, Bikenibeu Village",
		Utc:    "+12:00",
	},
	{
		Label:  "Pacific/Wake (GMT+12:00)",
		TzCode: "Pacific/Wake",
		Name:   "(GMT+12:00) Wake",
		Utc:    "+12:00",
	},
	{
		Label:  "Pacific/Wallis (GMT+12:00)",
		TzCode: "Pacific/Wallis",
		Name:   "(GMT+12:00) Mata-Utu, Leava, Alo",
		Utc:    "+12:00",
	},
	{
		Label:  "Pacific/Chatham (GMT+12:45)",
		TzCode: "Pacific/Chatham",
		Name:   "(GMT+12:45) Waitangi",
		Utc:    "+12:45",
	},
	{
		Label:  "Pacific/Apia (GMT+13:00)",
		TzCode: "Pacific/Apia",
		Name:   "(GMT+13:00) Apia, Asau, Mulifanua, Afega, Leulumoega",
		Utc:    "+13:00",
	},
	{
		Label:  "Pacific/Enderbury (GMT+13:00)",
		TzCode: "Pacific/Enderbury",
		Name:   "(GMT+13:00) Enderbury",
		Utc:    "+13:00",
	},
	{
		Label:  "Pacific/Fakaofo (GMT+13:00)",
		TzCode: "Pacific/Fakaofo",
		Name:   "(GMT+13:00) Atafu Village, Nukunonu, Fale old settlement",
		Utc:    "+13:00",
	},
	{
		Label:  "Pacific/Tongatapu (GMT+13:00)",
		TzCode: "Pacific/Tongatapu",
		Name:   "(GMT+13:00) Nuku‘alofa, Lapaha, Neiafu, Pangai, ‘Ohonua",
		Utc:    "+13:00",
	},
	{
		Label:  "Pacific/Kiritimati (GMT+14:00)",
		TzCode: "Pacific/Kiritimati",
		Name:   "(GMT+14:00) Kiritimati",
		Utc:    "+14:00",
	},
}
