name: "Renovate"
on:
  workflow_dispatch:
    inputs:
      DEBUG:
        description: "Enable debug logging"
        type: boolean
        required: false
        default: false
  schedule:
    - cron: "0 0 * * 1" # Triggers the workflow every Monday at midnight
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v43.0.15
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: ${{ inputs.DEBUG && 'debug' || 'info' }}
          RENOVATE_REPOSITORIES: '["${{ github.repository }}"]'
          RENOVATE_COMMIT_MESSAGE_SUFFIX: '{{#unless groupName}}{{#if (equals updateType "digest")}}(from {{currentDigestShort}}){{else}}(from {{currentVersion}}){{/if}}{{/unless}}'
          RENOVATE_LABELS: '["dependencies"]'
          RENOVATE_DEPENDENCY_DASHBOARD_LABELS: '["dependencies"]'
          RENOVATE_EXTENDS: '["config:best-practices","mergeConfidence:all-badges",":pinVersions","security:openssf-scorecard",":prHourlyLimitNone",":separateMultipleMajorReleases",":configMigration"]'
          RENOVATE_PLATFORM: "github"
